<?php
$config->modifycncc = new stdclass();
$config->modifycncc->create = new stdclass();
$config->modifycncc->copy   = new stdclass();
$config->modifycncc->edit   = new stdclass();
$config->modifycncc->change = new stdclass();
$config->modifycncc->link   = new stdclass();
$config->modifycncc->run    = new stdclass();
$config->modifycncc->create->requiredFields = 'changeStage,planBegin,planEnd,level,type,changeSource,applyUsercontact,changeSource,implementModality,isBusinessCooperate,isBusinessJudge,isBusinessAffect,property,desc,target,reason,node,changeContentAndMethod,step,techniqueCheck,test,checkList,feasibilityAnalysis,effect,businessFunctionAffect,backupDataCenterChangeSyncDesc,emergencyManageAffect,benchmarkVerificationType,mode,classify,risk,changeImpactAnalysis';
$config->modifycncc->copy->requiredFields   =  $config->modifycncc->create->requiredFields;
$config->modifycncc->edit->requiredFields   = $config->modifycncc->create->requiredFields;
$config->modifycncc->change->requiredFields = 'reviewer';
$config->modifycncc->link->requiredFields   = 'consumed,release';
$config->modifycncc->run->requiredFields    = 'consumed,result';
//审核节点默认选中
$config->modifycncc->create->setDefChosenReviewNodes = array(0, 1, 2, 3, 5, 6);

$config->modifycncc->editor = new stdclass();
$config->modifycncc->editor->create   = array('id' => 'reason,target,effect,plan,step,risk,test,checkList,businessAffect,changeContentAndMethod,techniqueCheck,businessCooperateContent,judgePlan,controlTableSteps,businessFunctionAffect,backupDataCenterChangeSyncDesc,emergencyManageAffect', 'tools' => 'modifycnccTools', 'height' => '100px');
$config->modifycncc->editor->copy     = array('id' => 'reason,target,effect,plan,step,risk,test,checkList,businessAffect,changeContentAndMethod,techniqueCheck,businessCooperateContent,judgePlan,controlTableSteps,businessFunctionAffect,backupDataCenterChangeSyncDesc,emergencyManageAffect', 'tools' => 'modifycnccTools', 'height' => '100px');
$config->modifycncc->editor->edit     = array('id' => 'reason,target,effect,plan,step,risk,test,checkList,businessAffect,changeContentAndMethod,techniqueCheck,businessCooperateContent,judgePlan,controlTableSteps,businessFunctionAffect,backupDataCenterChangeSyncDesc,emergencyManageAffect', 'tools' => 'modifycnccTools', 'height' => '100px');
$config->modifycncc->editor->confirm  = array('id' => 'conclusion,comment', 'tools' => 'simpleTools');
$config->modifycncc->editor->feedback = array('id' => 'reason,solution,progress', 'tools' => 'simpleTools');
$config->modifycncc->editor->view     = array('id' => 'comment,lastComment', 'tools' => 'simpleTools');
$config->modifycncc->editor->review   = array('id' => 'comment', 'tools' => 'simpleTools');
$config->modifycncc->editor->link     = array('id' => 'comment', 'tools' => 'simpleTools');
$config->modifycncc->editor->close    = array('id' => 'comment', 'tools' => 'simpleTools');
$config->modifycncc->editor->delete   = array('id' => 'comment', 'tools' => 'simpleTools');

$config->modifycncc->list = new stdclass();
$config->modifycncc->list->exportFields = 'code,status,createdBy,createdDept,
applyUsercontact,level,productRegistrationCode,node,operationType,app,isPayment,team,mode,classify,changeSource,changeStage,implementModality,type,isBusinessCooperate,
isBusinessJudge,isBusinessAffect,property,backspaceExpectedStartTime,backspaceExpectedEndTime,planBegin,planEnd,
fixType,project,problem,demand,productCode,relatedDemandNum,CNCCprojectIdUnique,changeRelation,
changeStatus,changeRemark,actualBegin,actualEnd,reasonCNCC,
desc,target,reason,changeContentAndMethod,step,techniqueCheck,test,checkList,cooperateDepNameList,businessCooperateContent,
judgeDep,judgePlan,controlTableFile,controlTableSteps,feasibilityAnalysis,risk,riskAnalysisEmergencyHandle,
effect,businessFunctionAffect,changeImpactAnalysis,backupDataCenterChangeSyncDesc,emergencyManageAffect,businessAffect,benchmarkVerificationType,verificationResults,
feedBackId,operationName,feedBackOperationType,depOddName,actualBegin,actualEnd,supply,changeNum,operationStaff,executionResults,result,internalSupply,problemDescription,resolveMethod,
createdDate,editedBy,editedDate,feedbackDate,closedBy,closedDate,
relatedOutwardDelivery,belongedOutwardDelivery,relatedTestingRequest,relatedProductEnroll,secondorderId,isReview,reviewReport,returnTimes,urgentSource,urgentReason,changeForm,automationTools,aadsReason';
//,isMakeAmends,actualDeliveryTime
/* Search. */
global $lang,$app;
$app->loadLang('modify');
$config->modifycncc->search['module'] = 'modifycncc';
$config->modifycncc->search['fields']['code']                     = $lang->modifycncc->code;
$config->modifycncc->search['fields']['status']                   = $lang->modifycncc->status;
$config->modifycncc->search['fields']['createdBy']                = $lang->modifycncc->createdBy;
$config->modifycncc->search['fields']['createdDept']              = $lang->modifycncc->createdDept;
$config->modifycncc->search['fields']['applyUsercontact']         = $lang->modifycncc->applyUsercontact;
$config->modifycncc->search['fields']['level']                    = $lang->modifycncc->level;
$config->modifycncc->search['fields']['productRegistrationCode']  = $lang->modifycncc->productRegistrationCode;
$config->modifycncc->search['fields']['productId']                = $lang->modifycncc->productName;
$config->modifycncc->search['fields']['node']                     = $lang->modifycncc->node;
$config->modifycncc->search['fields']['operationType']            = $lang->modifycncc->operationType;
$config->modifycncc->search['fields']['app']                      = $lang->modifycncc->app;
$config->modifycncc->search['fields']['urgentSource']             = '紧急来源';
$config->modifycncc->search['fields']['isPayment']                = $lang->modifycncc->isPayment;
$config->modifycncc->search['fields']['team']                     = $lang->modifycncc->team;
$config->modifycncc->search['fields']['mode']                     = $lang->modifycncc->mode;
$config->modifycncc->search['fields']['classify']                 = $lang->modifycncc->classify;
$config->modifycncc->search['fields']['changeSource']             = $lang->modifycncc->changeSource;
$config->modifycncc->search['fields']['changeStage']              = $lang->modifycncc->changeStage;
$config->modifycncc->search['fields']['implementModality']        = $lang->modifycncc->implementModality;
$config->modifycncc->search['fields']['type']                     = $lang->modifycncc->type;
$config->modifycncc->search['fields']['isBusinessCooperate']      = $lang->modifycncc->isBusinessCooperate;
$config->modifycncc->search['fields']['isBusinessJudge']          = $lang->modifycncc->isBusinessJudge;
$config->modifycncc->search['fields']['isBusinessAffect']         = $lang->modifycncc->isBusinessAffect;
$config->modifycncc->search['fields']['property']                 = $lang->modifycncc->property;
$config->modifycncc->search['fields']['backspaceExpectedStartTime']    = $lang->modifycncc->backspaceExpectedStartTime;
$config->modifycncc->search['fields']['backspaceExpectedEndTime']      = $lang->modifycncc->backspaceExpectedEndTime;
$config->modifycncc->search['fields']['planBegin']                 = $lang->modifycncc->planBegin;
$config->modifycncc->search['fields']['planEnd']                   = $lang->modifycncc->planEnd;
$config->modifycncc->search['fields']['fixType']                   = $lang->modifycncc->fixType;
$config->modifycncc->search['fields']['project']                   = $lang->modifycncc->project;
$config->modifycncc->search['fields']['relatedOutwardDelivery']    = $lang->modifycncc->relatedOutwardDelivery;
$config->modifycncc->search['fields']['belongedOutwardDelivery']   = $lang->modifycncc->belongedOutwardDelivery;
$config->modifycncc->search['fields']['relatedTestingRequest']     = $lang->modifycncc->relatedTestingRequest;
$config->modifycncc->search['fields']['relatedProductEnroll']      = $lang->modifycncc->relatedProductEnroll;
$config->modifycncc->search['fields']['returnTimes']               = $lang->modifycncc->returnTimes;
$config->modifycncc->search['fields']['ifMediumChanges']           = $lang->modifycncc->ifMediumChanges;
$config->modifycncc->search['fields']['problem']                   = $lang->modifycncc->problem;
$config->modifycncc->search['fields']['demand']                    = $lang->modifycncc->demand;
$config->modifycncc->search['fields']['productCode']               = $lang->modifycncc->productCode;
$config->modifycncc->search['fields']['relatedDemandNum']          = $lang->modifycncc->relatedDemandNum;
$config->modifycncc->search['fields']['CNCCprojectIdUnique']       = $lang->modifycncc->CNCCprojectIdUnique;
$config->modifycncc->search['fields']['changeRelation']            = $lang->modifycncc->changeRelation;
$config->modifycncc->search['fields']['changeStatus']              = $lang->modifycncc->changeStatus;
$config->modifycncc->search['fields']['changeRemark']              = $lang->modifycncc->changeRemark;
$config->modifycncc->search['fields']['actualBegin']               = $lang->modifycncc->actualBegin;
$config->modifycncc->search['fields']['actualEnd']                 = $lang->modifycncc->actualEnd;
$config->modifycncc->search['fields']['reasonCNCC']                = $lang->modifycncc->reasonCNCC;
$config->modifycncc->search['fields']['desc']                      = $lang->modifycncc->desc;
$config->modifycncc->search['fields']['target']                    = $lang->modifycncc->target;
$config->modifycncc->search['fields']['reason']                    = $lang->modifycncc->reason;
$config->modifycncc->search['fields']['changeContentAndMethod']    = $lang->modifycncc->changeContentAndMethod;
$config->modifycncc->search['fields']['step']                      = $lang->modifycncc->step;
$config->modifycncc->search['fields']['techniqueCheck']            = $lang->modifycncc->techniqueCheck;
$config->modifycncc->search['fields']['test']                      = $lang->modifycncc->test;
$config->modifycncc->search['fields']['cooperateDepNameList']      = $lang->modifycncc->cooperateDepNameList;
$config->modifycncc->search['fields']['checkList']                 = $lang->modifycncc->checkList;
$config->modifycncc->search['fields']['businessCooperateContent']  = $lang->modifycncc->businessCooperateContent;
$config->modifycncc->search['fields']['judgeDep']                  = $lang->modifycncc->judgeDep;
$config->modifycncc->search['fields']['judgePlan']                 = $lang->modifycncc->judgePlan;
$config->modifycncc->search['fields']['controlTableFile']          = $lang->modifycncc->controlTableFile;
$config->modifycncc->search['fields']['controlTableSteps']         = $lang->modifycncc->controlTableSteps;
$config->modifycncc->search['fields']['feasibilityAnalysis']       = $lang->modifycncc->feasibilityAnalysis;
$config->modifycncc->search['fields']['risk']                      = $lang->modifycncc->risk;
$config->modifycncc->search['fields']['riskAnalysisEmergencyHandle']       = $lang->modifycncc->riskAnalysisEmergencyHandle;
$config->modifycncc->search['fields']['effect']                            = $lang->modifycncc->effect;
$config->modifycncc->search['fields']['businessFunctionAffect']            = $lang->modifycncc->businessFunctionAffect;
$config->modifycncc->search['fields']['backupDataCenterChangeSyncDesc']    = $lang->modifycncc->backupDataCenterChangeSyncDesc;
$config->modifycncc->search['fields']['emergencyManageAffect']             = $lang->modifycncc->emergencyManageAffect;
$config->modifycncc->search['fields']['changeImpactAnalysis']             = $lang->modifycncc->changeImpactAnalysis;
$config->modifycncc->search['fields']['businessAffect']                    = $lang->modifycncc->businessAffect;
$config->modifycncc->search['fields']['benchmarkVerificationType']         = $lang->modifycncc->benchmarkVerificationType;
$config->modifycncc->search['fields']['verificationResults'] = $lang->modifycncc->verificationResults;
$config->modifycncc->search['fields']['result']              = $lang->modifycncc->result;
$config->modifycncc->search['fields']['createdDate']         = $lang->modifycncc->createdDate;
$config->modifycncc->search['fields']['editedBy']            = $lang->modifycncc->editedBy;
$config->modifycncc->search['fields']['editedDate']          = $lang->modifycncc->editedDate;
$config->modifycncc->search['fields']['feedbackDate']        = $lang->modifycncc->feedbackDate;
$config->modifycncc->search['fields']['closeBy']             = $lang->modifycncc->closeBy;
$config->modifycncc->search['fields']['closeDate']           = $lang->modifycncc->closeDate;
$config->modifycncc->search['fields']['secondorderId']           = $lang->modifycncc->secondorderId;
$config->modifycncc->search['fields']['isReview']           = $lang->modifycncc->isReview;
$config->modifycncc->search['fields']['reviewReport']           = $lang->modifycncc->reviewReport;
$config->modifycncc->search['fields']['changeForm']                = $lang->modifycncc->changeForm;
$config->modifycncc->search['fields']['automationTools']           = $lang->modifycncc->automationTools;
$config->modifycncc->search['fields']['aadsReason']           = $lang->modifycncc->aadsReason;
//$config->modifycncc->search['fields']['isMakeAmends']           = $lang->modify->isMakeAmends;

$config->modifycncc->search['params']['code']                 = array('operator' => 'include', 'control' => 'input', 'values' => '');
$config->modifycncc->search['params']['status']               = array('operator' => '=', 'control' => 'select', 'values' => $lang->modifycncc->statusList);
$config->modifycncc->search['params']['createdBy']            = array('operator' => '=', 'control' => 'select', 'values' => 'users');
$config->modifycncc->search['params']['createdDept']          = array('operator' => '=', 'control' => 'select', 'values' => '');
$config->modifycncc->search['params']['applyUsercontact']     = array('operator' => 'include', 'control' => 'input', 'values' => '');
$config->modifycncc->search['params']['level']                = array('operator' => '=', 'control' => 'select', 'values' => $lang->modifycncc->levelList);
$config->modifycncc->search['params']['productRegistrationCode'] = array('operator' => 'include', 'control' => 'input', 'values' => '');
$config->modifycncc->search['params']['productId']            = array('operator' => 'include', 'control' => 'select', 'values' => '');
$config->modifycncc->search['params']['node']        = array('operator' => 'include', 'control' => 'select', 'values' => $lang->modifycncc->nodeList);
$config->modifycncc->search['params']['operationType']        = array('operator' => 'include', 'control' => 'select', 'values' => $lang->modifycncc->operationTypeList);
$config->modifycncc->search['params']['app']         = array('operator' => 'include', 'control' => 'select', 'values' => array(0 => ''));
$config->modifycncc->search['params']['urgentSource']         = array('operator' => '=', 'control' => 'select', 'values' => array(0 => ''));
$config->modifycncc->search['params']['isPayment']   = array('operator' => 'include', 'control' => 'select', 'values' => array(0 => ''));
$config->modifycncc->search['params']['team']   = array('operator' => 'include', 'control' => 'input', 'values' => '');
$config->modifycncc->search['params']['mode']        = array('operator' => '=', 'control' => 'select', 'values' => $lang->modifycncc->modeList);
$config->modifycncc->search['params']['classify']    = array('operator' => '=', 'control' => 'select', 'values' => $lang->modifycncc->classifyList);
$config->modifycncc->search['params']['changeSource']    = array('operator' => '=', 'control' => 'select', 'values' => $lang->modifycncc->changeSourceList);
$config->modifycncc->search['params']['changeStage']    = array('operator' => '=', 'control' => 'select', 'values' => $lang->modifycncc->changeStageList);
$config->modifycncc->search['params']['implementModality']    = array('operator' => 'include', 'control' => 'select', 'values' => $lang->modifycncc->implementModalityList);
$config->modifycncc->search['params']['type']    = array('operator' => '=', 'control' => 'select', 'values' => $lang->modifycncc->typeList);
$config->modifycncc->search['params']['isBusinessCooperate']    = array('operator' => '=', 'control' => 'select', 'values' => $lang->modifycncc->isBusinessCooperateList);
$config->modifycncc->search['params']['isBusinessJudge']    = array('operator' => '=', 'control' => 'select', 'values' => $lang->modifycncc->isBusinessJudgeList);
$config->modifycncc->search['params']['isBusinessAffect']    = array('operator' => '=', 'control' => 'select', 'values' => $lang->modifycncc->isBusinessAffectList);
$config->modifycncc->search['params']['property']    = array('operator' => '=', 'control' => 'select', 'values' => $lang->modifycncc->propertyList);
$config->modifycncc->search['params']['backspaceExpectedStartTime']    = array('operator' => '=', 'control' => 'input', 'values' => '', 'class' => 'date');
$config->modifycncc->search['params']['backspaceExpectedEndTime']    = array('operator' => '=', 'control' => 'input', 'values' => '', 'class' => 'date');
$config->modifycncc->search['params']['planBegin']    = array('operator' => '=', 'control' => 'input', 'values' => '', 'class' => 'date');
$config->modifycncc->search['params']['planEnd']    = array('operator' => '=', 'control' => 'input', 'values' => '', 'class' => 'date');
$config->modifycncc->search['params']['fixType']     = array('operator' => '=', 'control' => 'select', 'values' => $lang->modifycncc->fixTypeList);
$config->modifycncc->search['params']['project']     = array('operator' => 'include', 'control' => 'select',  'values' => '');
$config->modifycncc->search['params']['relatedOutwardDelivery']      = array('operator' => 'include', 'control' => 'input',  'values' => '');
$config->modifycncc->search['params']['belongedOutwardDelivery']     = array('operator' => 'include', 'control' => 'input',  'values' => '');
$config->modifycncc->search['params']['relatedTestingRequest']       = array('operator' => 'include', 'control' => 'input',  'values' => '');
$config->modifycncc->search['params']['relatedProductEnroll']        = array('operator' => 'include', 'control' => 'input',  'values' => '');
$config->modifycncc->search['params']['returnTimes']                  = array('operator' => '=', 'control' => 'input', 'values' => '');
$config->modifycncc->search['params']['ifMediumChanges']              = array('operator' => '=', 'control' => 'select',  'values' => $lang->modifycncc->ifMediumChangesList);
$config->modifycncc->search['params']['problem']                      = array('operator' => 'include', 'control' => 'select',  'values' => '','mulit'=>true);
$config->modifycncc->search['params']['demand']     = array('operator' => 'include', 'control' => 'select',  'values' => '','mulit'=>true);
$config->modifycncc->search['params']['productCode']     = array('operator' => 'include', 'control' => 'input',  'values' => '');
$config->modifycncc->search['params']['relatedDemandNum']     = array('operator' => 'include', 'control' => 'select',  'values' => '');
$config->modifycncc->search['params']['CNCCprojectIdUnique']     = array('operator' => 'include', 'control' => 'select',  'values' => '');
$config->modifycncc->search['params']['changeRelation']     = array('operator' => 'include', 'control' => 'select',  'values' => '');
$config->modifycncc->search['params']['changeStatus']     = array('operator' => 'include', 'control' => 'input',  'values' => '');
$config->modifycncc->search['params']['changeRemark']     = array('operator' => 'include', 'control' => 'input',  'values' => '');
$config->modifycncc->search['params']['actualBegin']     = array('operator' => '=', 'control' => 'input', 'values' => '', 'class' => 'date');
$config->modifycncc->search['params']['actualEnd']     = array('operator' => '=', 'control' => 'input', 'values' => '', 'class' => 'date');
$config->modifycncc->search['params']['reasonCNCC']     = array('operator' => 'include', 'control' => 'input',  'values' => '');
$config->modifycncc->search['params']['desc']     = array('operator' => 'include', 'control' => 'input',  'values' => '');
$config->modifycncc->search['params']['target']     = array('operator' => 'include', 'control' => 'input',  'values' => '');
$config->modifycncc->search['params']['reason']      = array('operator' => 'include', 'control' => 'input', 'values' => '');
$config->modifycncc->search['params']['changeContentAndMethod']      = array('operator' => 'include', 'control' => 'input', 'values' => '');
$config->modifycncc->search['params']['step']        = array('operator' => 'include', 'control' => 'input', 'values' => '');
$config->modifycncc->search['params']['techniqueCheck']        = array('operator' => 'include', 'control' => 'input', 'values' => '');
$config->modifycncc->search['params']['test']        = array('operator' => 'include', 'control' => 'input', 'values' => '');
$config->modifycncc->search['params']['checkList']   = array('operator' => 'include', 'control' => 'input', 'values' => '');
$config->modifycncc->search['params']['cooperateDepNameList']   = array('operator' => '=', 'control' => 'select', 'values' => $lang->modifycncc->cooperateDepNameListList);
$config->modifycncc->search['params']['businessCooperateContent'] = array('operator' => 'include', 'control' => 'input', 'values' => '');
$config->modifycncc->search['params']['judgeDep'] = array('operator' => '=', 'control' => 'select', 'values' => $lang->modifycncc->judgeDepList);
$config->modifycncc->search['params']['judgePlan'] = array('operator' => 'include', 'control' => 'input', 'values' => '');
$config->modifycncc->search['params']['controlTableFile'] = array('operator' => 'include', 'control' => 'input', 'values' => '');
$config->modifycncc->search['params']['controlTableSteps'] = array('operator' => 'include', 'control' => 'input', 'values' => '');
$config->modifycncc->search['params']['feasibilityAnalysis'] = array('operator' => 'include', 'control' => 'input', 'values' => '');
$config->modifycncc->search['params']['risk']        = array('operator' => 'include', 'control' => 'input', 'values' => '');
$config->modifycncc->search['params']['riskAnalysisEmergencyHandle'] = array('operator' => 'include', 'control' => 'input', 'values' => '');
$config->modifycncc->search['params']['effect']      = array('operator' => 'include', 'control' => 'input', 'values' => '');
$config->modifycncc->search['params']['businessFunctionAffect']      = array('operator' => 'include', 'control' => 'input', 'values' => '');
$config->modifycncc->search['params']['backupDataCenterChangeSyncDesc']      = array('operator' => 'include', 'control' => 'input', 'values' => '');
$config->modifycncc->search['params']['emergencyManageAffect']      = array('operator' => 'include', 'control' => 'input', 'values' => '');
$config->modifycncc->search['params']['changeImpactAnalysis']      = array('operator' => 'include', 'control' => 'input', 'values' => '');
$config->modifycncc->search['params']['businessAffect']      = array('operator' => 'include', 'control' => 'input', 'values' => '');
$config->modifycncc->search['params']['benchmarkVerificationType']      = array('operator' => '=', 'control' => 'select', 'values' => $lang->modifycncc->benchmarkVerificationTypeList);
$config->modifycncc->search['params']['verificationResults'] = array('operator' => 'include', 'control' => 'input', 'values' => '');
$config->modifycncc->search['params']['result'] = array('operator' => 'include', 'control' => 'input', 'values' => '');
$config->modifycncc->search['params']['createdDate'] = array('operator' => '=', 'control' => 'input', 'values' => '', 'class' => 'date');
$config->modifycncc->search['params']['editedBy']    = array('operator' => '=', 'control' => 'select', 'values' => 'users');
$config->modifycncc->search['params']['editedDate']  = array('operator' => '=', 'control' => 'input', 'values' => '', 'class' => 'date');
$config->modifycncc->search['params']['feedbackDate']  = array('operator' => '=', 'control' => 'input', 'values' => '', 'class' => 'date');
$config->modifycncc->search['params']['closeBy']  = array('operator' => '=', 'control' => 'select', 'values' => 'users');
$config->modifycncc->search['params']['closeDate']  = array('operator' => '=', 'control' => 'input', 'values' => '', 'class' => 'date');
$config->modifycncc->search['params']['secondorderId'] = array('operator' => 'include', 'control' => 'select', 'values' => '');
$config->modifycncc->search['params']['isReview']      = array('operator' => '=', 'control' => 'select', 'values' => $lang->modifycncc->isReviewList);
$config->modifycncc->search['params']['reviewReport']      = array('operator' => 'include', 'control' => 'select', 'values' => '');
$config->modifycncc->search['params']['changeForm']                 = array('operator' => 'include', 'control' => 'select', 'values' => $lang->modifycncc->changeFormList,'mulit'=>true);
$config->modifycncc->search['params']['automationTools']                 = array('operator' => 'include', 'control' => 'select', 'values' => $lang->modifycncc->automationToolsList,'mulit'=>true);
//$config->modifycncc->search['params']['isMakeAmends']      = array('operator' => 'include', 'control' => 'select', 'values' => $lang->modify->isMakeAmendsList);
$config->modifycncc->search['params']['aadsReason'] = array('operator' => 'include', 'control' => 'input', 'values' => '');


$config->modifycncc->editor->editreturntimes   = array('id' => 'comment', 'tools' => 'simpleTools');