<?php
$config->modify = new stdclass();
$config->modify->create = new stdclass();
$config->modify->copy = new stdclass();
$config->modify->edit   = new stdclass();
$config->modify->change = new stdclass();
$config->modify->link   = new stdclass();
$config->modify->cancel   = new stdclass();
$config->modify->create->requiredFields = 'changeContentAndMethod,app,implementationForm,projectPlanId,level,node,mode,classify,changeSource,changeStage,implementModality,type,isBusinessCooperate,isBusinessJudge,isBusinessAffect,property,desc,planBegin,planEnd,target,reason,step,techniqueCheck,checkList,feasibilityAnalysis,effect,businessFunctionAffect,backupDataCenterChangeSyncDesc,emergencyManageAffect';
$config->modify->copy->requiredFields =  $config->modify->create->requiredFields;
$config->modify->edit->requiredFields   = $config->modify->create->requiredFields;
$config->modify->change->requiredFields = 'reviewer';
$config->modify->link->requiredFields   = 'release';
$config->modify->cancel->requiredFields = 'cancelReason';
//审核节点默认选中
$config->modify->create->setDefChosenReviewNodes = array(0, 1, 2, 3, 5, 6);

$config->modify->editor = new stdclass();
$config->modify->editor->confirm  = array('id' => 'conclusion,comment', 'tools' => 'simpleTools');
$config->modify->editor->feedback = array('id' => 'reason,solution,progress', 'tools' => 'simpleTools');
$config->modify->editor->view     = array('id' => 'comment,lastComment', 'tools' => 'simpleTools');
$config->modify->editor->review   = array('id' => 'comment', 'tools' => 'simpleTools');
$config->modify->editor->run      = array('id' => 'result,comment', 'tools' => 'simpleTools');
$config->modify->editor->link     = array('id' => 'comment', 'tools' => 'simpleTools');
$config->modify->editor->close    = array('id' => 'comment', 'tools' => 'simpleTools');
$config->modify->editor->delete   = array('id' => 'comment', 'tools' => 'simpleTools');
$config->modify->editor->caccel   = array('id' => 'comment', 'tools' => 'simpleTools');

$config->modify->list = new stdclass();
$config->modify->list->exportFields = 'code,status,createdBy,dealUser,createdDept,applyUsercontact,level,node,isReview,reviewReport,app,
isPayment,team,mode,classify,changeSource,changeStage,implementModality,type,isBusinessCooperate,isBusinessJudge,isBusinessAffect,property,backspaceExpectedStartTime,
backspaceExpectedEndTime,planBegin,planEnd,projectPlanId,testingRequestId,returnTime,ifMediumChanges,problemId,demandId,secondorderId,productInfoCode,
requirementId,changeStatus,changeRemark,actualBegin,actualEnd,returnReason,desc,target,reason,step,techniqueCheck,cooperateDepNameList,changeContentAndMethod,checkList,businessCooperateContent,
judgeDep,judgePlan,controlTableFile,controlTableSteps,feasibilityAnalysis,risk,riskAnalysisEmergencyHandle,effect,businessFunctionAffect,backupDataCenterChangeSyncDesc,
emergencyManageAffect,businessAffect,createdDate,editedBy,editedDate,feedbackDate,closedBy,closedDate,isDiskDelivery,jxLevel,implementationForm,preChange,postChange,
synImplement,pilotChange,promotionChange,productName,versionNum,releaseDate,launchDate,systemEnAbbreviation,researchDept,projectManager,revertReason,revertReasonChild,involveDatabase';
//,isMakeAmends,actualDeliveryTime

/* Search. */
global $lang;
$config->modify->search['module'] = 'modify';
$config->modify->search['fields']['code']                     = $lang->modify->code;
$config->modify->search['fields']['status']                   = $lang->modify->status;
$config->modify->search['fields']['createdBy']                = $lang->modify->createdBy;
$config->modify->search['fields']['createdDept']              = $lang->modify->createdDept;
$config->modify->search['fields']['dealUser']                 = $lang->modify->dealUser;
$config->modify->search['fields']['applyUsercontact']         = $lang->modify->applyUsercontact;
$config->modify->search['fields']['level']                    = $lang->modify->level;
$config->modify->search['fields']['productRegistrationCode']  = $lang->modify->productRegistrationCode;
$config->modify->search['fields']['productId']                = $lang->modify->productName;
$config->modify->search['fields']['node']                     = $lang->modify->node;
// $config->modify->search['fields']['operationType']            = $lang->modify->operationType;
$config->modify->search['fields']['isReview']                 = $lang->modify->isReview;
$config->modify->search['fields']['reviewReport']             = $lang->modify->reviewReport;
$config->modify->search['fields']['app']                      = $lang->modify->app;
$config->modify->search['fields']['isPayment']                = $lang->modify->isPayment;
$config->modify->search['fields']['team']                     = $lang->modify->team;
$config->modify->search['fields']['mode']                     = $lang->modify->mode;
$config->modify->search['fields']['classify']                 = $lang->modify->classify;
$config->modify->search['fields']['changeSource']             = $lang->modify->changeSource;
$config->modify->search['fields']['changeStage']              = $lang->modify->changeStage;
$config->modify->search['fields']['implementModality']        = $lang->modify->implementModality;
$config->modify->search['fields']['type']                     = $lang->modify->type;
$config->modify->search['fields']['isBusinessCooperate']      = $lang->modify->isBusinessCooperate;
$config->modify->search['fields']['isBusinessJudge']          = $lang->modify->isBusinessJudge;
$config->modify->search['fields']['isBusinessAffect']         = $lang->modify->isBusinessAffect;
$config->modify->search['fields']['property']                 = $lang->modify->property;
$config->modify->search['fields']['backspaceExpectedStartTime']    = $lang->modify->backspaceExpectedStartTime;
$config->modify->search['fields']['backspaceExpectedEndTime']      = $lang->modify->backspaceExpectedEndTime;
$config->modify->search['fields']['planBegin']                 = $lang->modify->planBegin;
$config->modify->search['fields']['planEnd']                   = $lang->modify->planEnd;
$config->modify->search['fields']['projectPlanId']             = $lang->modify->projectPlanId;
$config->modify->search['fields']['testingRequestId']          = $lang->modify->relatedTestingRequest;
// $config->modify->search['fields']['productenrollId']           = $lang->modify->relatedProductEnroll;
$config->modify->search['fields']['returnTime']                = $lang->modify->returnTime;
$config->modify->search['fields']['ifMediumChanges']           = $lang->modify->ifMediumChanges;
$config->modify->search['fields']['problemId']                 = $lang->modify->problemId;
$config->modify->search['fields']['demandId']                  = $lang->modify->demandId;
$config->modify->search['fields']['secondorderId']             = $lang->modify->secondorderId;
$config->modify->search['fields']['productInfoCode']           = $lang->modify->productInfoCode;
$config->modify->search['fields']['requirementId']             = $lang->modify->requirementId;
$config->modify->search['fields']['changeStatus']              = $lang->modify->changeStatus;
$config->modify->search['fields']['changeRemark']              = $lang->modify->changeRemark;
$config->modify->search['fields']['actualBegin']               = $lang->modify->actualBegin;
$config->modify->search['fields']['actualEnd']                 = $lang->modify->actualEnd;
$config->modify->search['fields']['returnReason']              = $lang->modify->returnReason;
$config->modify->search['fields']['desc']                      = $lang->modify->desc;
$config->modify->search['fields']['target']                    = $lang->modify->target;
$config->modify->search['fields']['reason']                    = $lang->modify->reason;
// $config->modify->search['fields']['changeContentAndMethod']    = $lang->modify->changeContentAndMethod;
$config->modify->search['fields']['step']                      = $lang->modify->step;
$config->modify->search['fields']['techniqueCheck']            = $lang->modify->techniqueCheck;
// $config->modify->search['fields']['test']                      = $lang->modify->test;
$config->modify->search['fields']['cooperateDepNameList']      = $lang->modify->cooperateDepNameList;
$config->modify->search['fields']['changeContentAndMethod']    = $lang->modify->changeContentAndMethod;
$config->modify->search['fields']['checkList']                 = $lang->modify->checkList;
$config->modify->search['fields']['businessCooperateContent']  = $lang->modify->businessCooperateContent;
$config->modify->search['fields']['judgeDep']                  = $lang->modify->judgeDep;
$config->modify->search['fields']['judgePlan']                 = $lang->modify->judgePlan;
$config->modify->search['fields']['controlTableFile']          = $lang->modify->controlTableFile;
$config->modify->search['fields']['controlTableSteps']         = $lang->modify->controlTableSteps;
$config->modify->search['fields']['feasibilityAnalysis']       = $lang->modify->feasibilityAnalysis;
$config->modify->search['fields']['risk']                      = $lang->modify->risk;
$config->modify->search['fields']['riskAnalysisEmergencyHandle']       = $lang->modify->riskAnalysisEmergencyHandle;
$config->modify->search['fields']['effect']                            = $lang->modify->effect;
$config->modify->search['fields']['businessFunctionAffect']            = $lang->modify->businessFunctionAffect;
$config->modify->search['fields']['backupDataCenterChangeSyncDesc']    = $lang->modify->backupDataCenterChangeSyncDesc;
$config->modify->search['fields']['emergencyManageAffect']             = $lang->modify->emergencyManageAffect;
$config->modify->search['fields']['businessAffect']                    = $lang->modify->businessAffect;
// $config->modify->search['fields']['verificationResults'] = $lang->modify->verificationResults;
// $config->modify->search['fields']['result']              = $lang->modify->result;
$config->modify->search['fields']['createdDate']         = $lang->modify->createdDate;
$config->modify->search['fields']['editedBy']            = $lang->modify->editedBy;
$config->modify->search['fields']['editedDate']          = $lang->modify->editedDate;
$config->modify->search['fields']['feedbackDate']        = $lang->modify->feedbackDate;
$config->modify->search['fields']['closedBy']             = $lang->modify->closeBy;
$config->modify->search['fields']['closedDate']           = $lang->modify->closeDate;
$config->modify->search['fields']['isDiskDelivery']           = $lang->modify->isDiskDelivery;
$config->modify->search['fields']['jxLevel']           = $lang->modify->jxLevel;
$config->modify->search['fields']['preChange']           = $lang->modify->preChange;
$config->modify->search['fields']['postChange']           = $lang->modify->postChange;
$config->modify->search['fields']['synImplement']           = $lang->modify->synImplement;
$config->modify->search['fields']['pilotChange']           = $lang->modify->pilotChange;
$config->modify->search['fields']['promotionChange']           = $lang->modify->promotionChange;
$config->modify->search['fields']['revertReason']           = $lang->modify->revertReason;
$config->modify->search['fields']['involveDatabase']           = $lang->modify->involveDatabase;
//$config->modify->search['fields']['isMakeAmends']           = $lang->modify->isMakeAmends;




$config->modify->search['params']['code']                       = array('operator' => 'include', 'control' => 'input', 'values' => '');
$config->modify->search['params']['status']                     = array('operator' => '=', 'control' => 'select', 'values' => $lang->modify->statusList);
$config->modify->search['params']['createdBy']                  = array('operator' => '=', 'control' => 'select', 'values' => 'users');
$config->modify->search['params']['createdDept']                = array('operator' => '=', 'control' => 'select', 'values' => '');
$config->modify->search['params']['dealUser']                   = array('operator' => '=', 'control' => 'select', 'values' => 'users');
$config->modify->search['params']['applyUsercontact']           = array('operator' => 'include', 'control' => 'input', 'values' => '');
$config->modify->search['params']['level']                      = array('operator' => '=', 'control' => 'select', 'values' => $lang->modify->levelList);
$config->modify->search['params']['productRegistrationCode']    = array('operator' => '=', 'control' => 'input', 'values' => '');
$config->modify->search['params']['productId']                  = array('operator' => 'include', 'control' => 'select', 'values' => '');
$config->modify->search['params']['node']                       = array('operator' => 'include', 'control' => 'select', 'values' => $lang->modify->nodeList);
// $config->modify->search['params']['operationType']              = array('operator' => 'include', 'control' => 'select', 'values' => $lang->modify->operationTypeList);
$config->modify->search['params']['isReview']                   = array('operator' => '=', 'control' => 'select', 'values' => $lang->modify->isReviewList);
// $config->modify->search['params']['isReviewPass']               = array('operator' => '=', 'control' => 'select', 'values' => $lang->modify->isReviewPassList);
$config->modify->search['params']['reviewReport']               = array('operator' => 'include', 'control' => 'select', 'values' => '');
$config->modify->search['params']['app']                        = array('operator' => 'include', 'control' => 'select', 'values' => array(0 => ''),'mulit'=>true);
$config->modify->search['params']['isPayment']                  = array('operator' => 'include', 'control' => 'select', 'values' => array(0 => ''));
$config->modify->search['params']['team']                       = array('operator' => 'include', 'control' => 'select', 'values' => '');
$config->modify->search['params']['mode']                       = array('operator' => '=', 'control' => 'select', 'values' => $lang->modify->modeList);
$config->modify->search['params']['classify']                   = array('operator' => '=', 'control' => 'select', 'values' => $lang->modify->classifyList);
$config->modify->search['params']['changeSource']               = array('operator' => '=', 'control' => 'select', 'values' => $lang->modify->changeSourceList);
$config->modify->search['params']['changeStage']                = array('operator' => '=', 'control' => 'select', 'values' => $lang->modify->changeStageList);
$config->modify->search['params']['implementModality']          = array('operator' => '=', 'control' => 'select', 'values' => $lang->modify->implementModalityList);
$config->modify->search['params']['type']                       = array('operator' => '=', 'control' => 'select', 'values' => $lang->modify->typeList);
$config->modify->search['params']['isBusinessCooperate']        = array('operator' => '=', 'control' => 'select', 'values' => $lang->modify->isBusinessCooperateList);
$config->modify->search['params']['isBusinessJudge']            = array('operator' => '=', 'control' => 'select', 'values' => $lang->modify->isBusinessJudgeList);
$config->modify->search['params']['isBusinessAffect']           = array('operator' => '=', 'control' => 'select', 'values' => $lang->modify->isBusinessAffectList);
$config->modify->search['params']['property']                   = array('operator' => '=', 'control' => 'select', 'values' => $lang->modify->propertyList);
$config->modify->search['params']['backspaceExpectedStartTime'] = array('operator' => '=', 'control' => 'input', 'values' => '', 'class' => 'date');
$config->modify->search['params']['backspaceExpectedEndTime']   = array('operator' => '=', 'control' => 'input', 'values' => '', 'class' => 'date');
$config->modify->search['params']['planBegin']                  = array('operator' => '=', 'control' => 'input', 'values' => '', 'class' => 'date');
$config->modify->search['params']['planEnd']                    = array('operator' => '=', 'control' => 'input', 'values' => '', 'class' => 'date');
$config->modify->search['params']['projectPlanId']              = array('operator' => '=', 'control' => 'select',  'values' => '');
$config->modify->search['params']['testingRequestId']           = array('operator' => '=', 'control' => 'select',  'values' => '');
// $config->modify->search['params']['productenrollId']            = array('operator' => 'include', 'control' => 'select',  'values' => '');
$config->modify->search['params']['returnTime']                 = array('operator' => '=', 'control' => 'input', 'values' => '');
$config->modify->search['params']['ifMediumChanges']            = array('operator' => '=', 'control' => 'select',  'values' => $lang->modify->ifMediumChangesList);
$config->modify->search['params']['problemId']                  = array('operator' => 'include', 'control' => 'select',  'values' => '','mulit'=>true);
$config->modify->search['params']['demandId']                   = array('operator' => 'include', 'control' => 'select',  'values' => '','mulit'=>true);
$config->modify->search['params']['secondorderId']              = array('operator' => 'include', 'control' => 'select',  'values' => '');
$config->modify->search['params']['productInfoCode']            = array('operator' => 'include', 'control' => 'input',  'values' => '');
$config->modify->search['params']['requirementId']              = array('operator' => 'include', 'control' => 'select',  'values' => '','mulit'=>true);
$config->modify->search['params']['changeStatus']               = array('operator' => '=', 'control' => 'select',  'values' => $lang->modify->changeStatusList);
$config->modify->search['params']['changeRemark']               = array('operator' => 'include', 'control' => 'input',  'values' => '');
$config->modify->search['params']['actualBegin']                = array('operator' => '=', 'control' => 'input', 'values' => '', 'class' => 'date');
$config->modify->search['params']['actualEnd']                  = array('operator' => '=', 'control' => 'input', 'values' => '', 'class' => 'date');
$config->modify->search['params']['returnReason']               = array('operator' => 'include', 'control' => 'input',  'values' => '');
$config->modify->search['params']['desc']                       = array('operator' => 'include', 'control' => 'input',  'values' => '');
$config->modify->search['params']['target']                     = array('operator' => 'include', 'control' => 'input',  'values' => '');
$config->modify->search['params']['reason']                     = array('operator' => 'include', 'control' => 'input', 'values' => '');
// $config->modify->search['params']['changeContentAndMethod']     = array('operator' => 'include', 'control' => 'input', 'values' => '');
$config->modify->search['params']['step']                       = array('operator' => 'include', 'control' => 'input', 'values' => '');
$config->modify->search['params']['techniqueCheck']             = array('operator' => 'include', 'control' => 'input', 'values' => '');
// $config->modify->search['params']['test']                       = array('operator' => 'include', 'control' => 'input', 'values' => '');
$config->modify->search['params']['changeContentAndMethod']     = array('operator' => 'include', 'control' => 'input', 'values' => '');
$config->modify->search['params']['checkList']                  = array('operator' => 'include', 'control' => 'input', 'values' => '');
$config->modify->search['params']['cooperateDepNameList']       = array('operator' => '=', 'control' => 'select', 'values' => $lang->modify->cooperateDepNameListList);
$config->modify->search['params']['businessCooperateContent']   = array('operator' => 'include', 'control' => 'input', 'values' => '');
$config->modify->search['params']['judgeDep']                   = array('operator' => '=', 'control' => 'select', 'values' => $lang->modify->judgeDepList);
$config->modify->search['params']['judgePlan']                  = array('operator' => 'include', 'control' => 'input', 'values' => '');
$config->modify->search['params']['controlTableFile']           = array('operator' => 'include', 'control' => 'input', 'values' => '');
$config->modify->search['params']['controlTableSteps']          = array('operator' => 'include', 'control' => 'input', 'values' => '');
$config->modify->search['params']['feasibilityAnalysis']        = array('operator' => 'include', 'control' => 'select', 'values' => $lang->modify->feasibilityAnalysisList);
$config->modify->search['params']['risk']                       = array('operator' => 'include', 'control' => 'input', 'values' => '');
$config->modify->search['params']['riskAnalysisEmergencyHandle'] = array('operator' => 'include', 'control' => 'input', 'values' => '');
$config->modify->search['params']['effect']                     = array('operator' => 'include', 'control' => 'input', 'values' => '');
$config->modify->search['params']['businessFunctionAffect']     = array('operator' => 'include', 'control' => 'input', 'values' => '');
$config->modify->search['params']['backupDataCenterChangeSyncDesc'] = array('operator' => 'include', 'control' => 'input', 'values' => '');
$config->modify->search['params']['emergencyManageAffect']      = array('operator' => 'include', 'control' => 'input', 'values' => '');
$config->modify->search['params']['businessAffect']             = array('operator' => 'include', 'control' => 'input', 'values' => '');
// $config->modify->search['params']['verificationResults']        = array('operator' => 'include', 'control' => 'input', 'values' => '');
// $config->modify->search['params']['result']                     = array('operator' => 'include', 'control' => 'input', 'values' => '');
$config->modify->search['params']['createdDate']                = array('operator' => '=', 'control' => 'input', 'values' => '', 'class' => 'date');
$config->modify->search['params']['editedBy']                   = array('operator' => '=', 'control' => 'select', 'values' => 'users');
$config->modify->search['params']['editedDate']                 = array('operator' => '=', 'control' => 'input', 'values' => '', 'class' => 'date');
$config->modify->search['params']['feedbackDate']               = array('operator' => '=', 'control' => 'input', 'values' => '', 'class' => 'date');
$config->modify->search['params']['closedBy']                   = array('operator' => '=', 'control' => 'select', 'values' => 'users');
$config->modify->search['params']['closedDate']                 = array('operator' => '=', 'control' => 'input', 'values' => '', 'class' => 'date');
$config->modify->search['params']['isDiskDelivery']             = array('operator' => '=', 'control' => 'select', 'values' => $lang->modify->isDiskDeliveryList);
$config->modify->search['params']['jxLevel']                    = array('operator' => '=', 'control' => 'select', 'values' => $lang->modify->levelJxList);
$config->modify->search['params']['preChange']                  = array('operator' => 'include', 'control' => 'input', 'values' => '');
$config->modify->search['params']['postChange']                 = array('operator' => 'include', 'control' => 'input', 'values' => '');
$config->modify->search['params']['synImplement']               = array('operator' => 'include', 'control' => 'input', 'values' => '');
$config->modify->search['params']['pilotChange']                = array('operator' => 'include', 'control' => 'input', 'values' => '');
$config->modify->search['params']['promotionChange']            = array('operator' => 'include', 'control' => 'input', 'values' => '');
$config->modify->search['params']['revertReason']               = array('operator' => 'include', 'control' => 'select', 'values' => '');
$config->modify->search['params']['involveDatabase']            = array('operator' => 'include', 'control' => 'select', 'values' => $lang->modify->materialIsReviewList);
//$config->modify->search['params']['isMakeAmends']     = array('operator' => 'include', 'control' => 'select', 'values' => $lang->modify->isMakeAmendsList);

