<?php
$filter->opinion = new stdclass();
$filter->opinion->export = new stdclass();
$filter->opinion->export->cookie['checkedItem'] = 'reg::checked';

$filter->cm = new stdclass();
$filter->cm->export = new stdclass();
$filter->cm->export->cookie['checkedItem'] = 'reg::checked';

$filter->application = new stdclass();
$filter->application->export = new stdclass();
$filter->application->export->cookie = array();
$filter->application->export->cookie['checkedItem'] = 'reg::checked';

$filter->weeklyreport = new stdclass();
$filter->weeklyreport->export = new stdclass();
$filter->weeklyreport->export->cookie = array();
$filter->weeklyreport->export->cookie['checkedItem'] = 'reg::checked';

$filter->doclib = new stdclass();
$filter->doclib->default = new stdclass();
$filter->doclib->default->get['doclibPath'] = 'reg::any';
$filter->doclib->ajaxwopifiles = new stdclass();
$filter->doclib->ajaxwopifiles->get['access_token'] = 'code';

$filter->projectdoc = new stdclass();
$filter->projectdoc->default = new stdclass();
$filter->projectdoc->default->get['doclibPath'] = 'reg::any';
$filter->projectdoc->ajaxwopifiles = new stdclass();
$filter->projectdoc->ajaxwopifiles->get['access_token'] = 'code';

define('TABLE_OPINION',                 '`' . $config->db->prefix . 'opinion`');
define('TABLE_OPINIONINSIDE',           '`' . $config->db->prefix . 'opinioninside`');
define('TABLE_OPINIONCHANGE',           '`' . $config->db->prefix . 'opinionchange`');
define('TABLE_REQUIREMENT',             '`' . $config->db->prefix . 'requirement`');
define('TABLE_REQUIREMENTINSIDE',       '`' . $config->db->prefix . 'requirementinside`');
define('TABLE_REQUIREMENTSPEC',         '`' . $config->db->prefix . 'requirementspec`');
define('TABLE_REQUIREMENTCHANGE',       '`' . $config->db->prefix . 'requirementchange`');
define('TABLE_REQUIREMENTCHANGEOUTSIDE','`' . $config->db->prefix . 'requirementchangeoutside`');
define('TABLE_APPLICATION',             '`' . $config->db->prefix . 'application`');
define('TABLE_PROJECTPLAN',             '`' . $config->db->prefix . 'projectplan`');
define('TABLE_PROJECTPLANMSRELATION',             '`' . $config->db->prefix . 'projectplanmsrelation`');
define('TABLE_PROJECTPLAN_ISDELAY_LOG',             '`' . $config->db->prefix . 'projectplan_isdelay_log`');
define('TABLE_OUTSIDEPLAN',             '`' . $config->db->prefix . 'outsideplan`');
define('TABLE_OUTSIDEPLANSUBPROJECTS',  '`' . $config->db->prefix . 'outsideplansubprojects`');
define('TABLE_OUTSIDEPLANTASKS',        '`' . $config->db->prefix . 'outsideplantasks`');
define('TABLE_REVIEWNODE',              '`' . $config->db->prefix . 'reviewnode`');
define('TABLE_REVIEWER',                '`' . $config->db->prefix . 'reviewer`');
define('TABLE_REVIEWOBJECT',            '`' . $config->db->prefix . 'reviewobject`');
define('TABLE_PROJECTCREATION',         '`' . $config->db->prefix . 'projectcreation`');
define('TABLE_PROJECTPLANCHANGE',       '`' . $config->db->prefix . 'projectplanchange`');
define('TABLE_PROJECTPLANEDIT',         '`' . $config->db->prefix . 'projectplanedit`');
define('TABLE_PROJECTPLANACTION',         '`' . $config->db->prefix . 'projectplan_action`');
define('TABLE_PROJECTWEEKLYREPORT',     '`' . $config->db->prefix . 'projectweeklyreport`');
define('TABLE_PROJECTWEEKLYREPORT_INSIDEMILE',     '`' . $config->db->prefix . 'projectweeklyreport_insidemile`');
define('TABLE_PROJECTWEEKLYREPORT_MEDIUM',     '`' . $config->db->prefix . 'projectweeklyreport_medium`');
define('TABLE_PROJECTWEEKLYREPORT_OUTMILE',     '`' . $config->db->prefix . 'projectweeklyreport_outmile`');
define('TABLE_PROJECTWEEKLYREPORT_RISK',     '`' . $config->db->prefix . 'projectweeklyreport_risk`');
define('TABLE_OUTSIDEPROJECTWEEKLYREPORT',     '`' . $config->db->prefix . 'outsideprojectweeklyreport`');
define('TABLE_OUTSIDEPROJECTWEEKLYREPORT_QUEUE',     '`' . $config->db->prefix . 'outsideprojectweeklyreport_queue`');
define('TABLE_PROBLEM',                 '`' . $config->db->prefix . 'problem`');
define('TABLE_DEMAND',                  '`' . $config->db->prefix . 'demand`');
define('TABLE_DEMANDINSIDE',            '`' . $config->db->prefix . 'demand`');
define('TABLE_DOCUMENT',                '`' . $config->db->prefix . 'document`');
define('TABLE_DOCBRANCH',               '`' . $config->db->prefix . 'docbranch`');
define('TABLE_DOCHISTORY',              '`' . $config->db->prefix . 'dochistory`');
define('TABLE_DOCFILES',                '`' . $config->db->prefix . 'docfiles`');
define('TABLE_PROCESSIMPROVE',          '`' . $config->db->prefix . 'processimprove`');
define('TABLE_EPGPROCESS',              '`' . $config->db->prefix . 'epgprocess`');
define('TABLE_INFO',                    '`' . $config->db->prefix . 'info`');
define('TABLE_INFO_QZ',                 '`' . $config->db->prefix . 'infoqz`');
define('TABLE_DUTY',                    '`' . $config->db->prefix . 'duty`');
define('TABLE_MODIFY',                  '`' . $config->db->prefix . 'modify`');
define('TABLE_MODIFYCNCC',              '`' . $config->db->prefix . 'modifycncc`');
define('TABLE_CBPPROJECT',              '`' . $config->db->prefix . 'cbpproject`');
define('TABLE_PRODUCTREQUIREMENT',      '`' . $config->db->prefix . 'productrequirement`');
define('TABLE_PRODUCTLINE',             '`' . $config->db->prefix . 'productline`');
define('TABLE_CONSUMED',                '`' . $config->db->prefix . 'consumed`');
define('TABLE_PROJECTDOCUMENT',         '`' . $config->db->prefix . 'projectdocument`');
define('TABLE_CHANGE',                  '`' . $config->db->prefix . 'change`');
define('TABLE_SECONDLINE',              '`' . $config->db->prefix . 'secondline`');
define('TABLE_BASELINE',                '`' . $config->db->prefix . 'baseline`');
define('TABLE_CMITEM',                  '`' . $config->db->prefix . 'cmitem`');
define('TABLE_PRODUCTCODE',             '`' . $config->db->prefix . 'productcode`');
define('TABLE_PIPELINE',                '`' . $config->db->prefix . 'pipeline`');
define('TABLE_REQUESTLOG',              '`' . $config->db->prefix . 'requestlog`');
define('TABLE_MAILRECORD',              '`' . $config->db->prefix . 'mailrecord`');
define('TABLE_RELATIONPLAN',            '`' . $config->db->prefix . 'relationplan`');
define('TABLE_EXECUTIONSPEC',           '`' . $config->db->prefix . 'executionspec`');
define('TABLE_PARTITION',               '`' . $config->db->prefix . 'partition`');
define('TABLE_DOWNLOADS',               '`' . $config->db->prefix . 'downloads`');
define('TABLE_KV',                      '`' . $config->db->prefix . 'kv`');
define('TABLE_TESTINGREQUEST',          '`' . $config->db->prefix . 'testingrequest`');
define('TABLE_PRODUCTENROLL',           '`' . $config->db->prefix . 'productenroll`');
define('TABLE_OUTWARDDELIVERY',         '`' . $config->db->prefix . 'outwarddelivery`');
define('TABLE_REVIEW_MEETING',          '`' . $config->db->prefix . 'review_meeting`');
define('TABLE_REVIEW_MEETING_DETAIL',   '`' . $config->db->prefix . 'review_meeting_detail`');
define('TABLE_REVIEW_MEETING_MAIL',     '`' . $config->db->prefix . 'review_meeting_mail`');

define('TABLE_LDAPUPDATE',              '`' . $config->db->prefix . 'ldapupdate`');
define('TABLE_LDAPDEPT',                '`' . $config->db->prefix . 'ldapdept`');
define('TABLE_LDAPUSER',                '`' . $config->db->prefix . 'ldapuser`');
define('TABLE_LDAPHISTORY',             '`' . $config->db->prefix . 'ldaphistory`');
define('TABLE_COMPONENT',               '`' . $config->db->prefix . 'component`');
define('TABLE_DATAUSE',                 '`' . $config->db->prefix . 'datause`');
define('TABLE_TOREAD',                  '`' . $config->db->prefix . 'toread`');
define('TABLE_COPYRIGHTQZ',             '`' . $config->db->prefix . 'copyrightqz`');
define('TABLE_COPYRIGHT',               '`' . $config->db->prefix . 'copyright`');
define('TABLE_ARCHIVE',                 '`' . $config->db->prefix . 'archive`');

define('TABLE_COMPONENT_RELEASE',               '`' . $config->db->prefix . 'component_release`');
define('TABLE_COMPONENT_VERSION',               '`' . $config->db->prefix . 'component_version`');
define('TABLE_COMPONENT_ACCOUNT',               '`' . $config->db->prefix . 'component_account`');

define('TABLE_RESIDENT_SUPPORT_TEMPLATE',    '`' . $config->db->prefix . 'resident_support_template`');
define('TABLE_RESIDENT_SUPPORT_TEMPLATE_DEPT',    '`' . $config->db->prefix . 'resident_support_template_dept`');
define('TABLE_RESIDENT_SUPPORT_DAY',         '`' . $config->db->prefix . 'resident_support_day`');
define('TABLE_RESIDENT_SUPPORT_DAY_DETAIL',  '`' . $config->db->prefix . 'resident_support_day_detail`');
define('TABLE_RESIDENT_SUPPORT_WORK',        '`' . $config->db->prefix . 'resident_support_work`');
define('TABLE_RESIDENT_SUPPORT_WORK_DETAIL', '`' . $config->db->prefix . 'resident_support_work_detail`');
define('TABLE_RESIDENT_SUPPORT_WORK_DETAIL_DRAFT', '`' . $config->db->prefix . 'resident_support_work_detail_draft`');
define('TABLE_RESIDENT_SUPPORT_WORK_DRAFT', '`' . $config->db->prefix . 'resident_support_work_draft`');

define('TABLE_KANBAN',       '`' . $config->db->prefix . 'kanban`');
define('TABLE_KANBANSPACE',  '`' . $config->db->prefix . 'kanbanspace`');
define('TABLE_KANBANREGION', '`' . $config->db->prefix . 'kanbanregion`');
define('TABLE_KANBANLANE',   '`' . $config->db->prefix . 'kanbanlane`');
define('TABLE_KANBANCOLUMN', '`' . $config->db->prefix . 'kanbancolumn`');
define('TABLE_KANBANORDER',  '`' . $config->db->prefix . 'kanbanorder`');
define('TABLE_KANBANGROUP',  '`' . $config->db->prefix . 'kanbangroup`');
define('TABLE_KANBANCARD',   '`' . $config->db->prefix . 'kanbancard`');
define('TABLE_KANBANCELL',   '`' . $config->db->prefix . 'kanbancell`');
define('TABLE_KANBANTYPE',   '`' . $config->db->prefix . 'kanbantype`');

define('TABLE_SECTRANSFER',   '`' . $config->db->prefix . 'sectransfer`');
define('TABLE_CLOSINGITEM',            '`' . $config->db->prefix . 'closingitem`');
define('TABLE_CLOSINGADVISE',          '`' . $config->db->prefix . 'closingadvise`');
define('TABLE_OSSPCHANGE',   '`' . $config->db->prefix . 'osspchange`');
define('TABLE_COMPONENT_PUBLIC_ACCOUNT',   '`' . $config->db->prefix . 'component_public_account`');
if(!defined('TABLE_DEMANDCOLLECTION'))   define('TABLE_DEMANDCOLLECTION', '`' . $config->db->prefix . 'demandcollection`');

define('TABLE_TASK_DEMAND_PROBLEM', '`' . $config->db->prefix . 'task_demand_problem`');
if(!defined('TABLE_SECONDORDER'))        define('TABLE_SECONDORDER', '`' . $config->db->prefix . 'secondorder`');
define('TABLE_DEFECT', '`' . $config->db->prefix . 'defect`');
define('TABLE_SAFETY_PARAM', '`' . $config->db->prefix . 'safety_param`');
define('TABLE_SAFETY_SCORE', '`' . $config->db->prefix . 'safety_score`');
if(!defined('TABLE_FLOW_HANDBOOK'))   define('TABLE_FLOW_HANDBOOK', '`' . $config->db->prefix . 'flow_handbook`');
define('TABLE_DELAY', '`' . $config->db->prefix . 'delay`');
define('TABLE_AUTHORIZATION',   '`' . $config->db->prefix . 'authorization`');
define('TABLE_IMPLEMENTIONPLAN',   '`' . $config->db->prefix . 'implementionplan`');
define('TABLE_WORKREPORT',   '`' . $config->db->prefix . 'workreport`');
define('TABLE_PUTPRODUCTION',   '`' . $config->db->prefix . 'putproduction`');
define('TABLE_PRODUCTIONCHANGE',   '`' . $config->db->prefix . 'productionchange`');
define('TABLE_IWFP',   '`' . $config->db->prefix . 'iwfp`');
define('TABLE_CMDBSYNC',   '`' . $config->db->prefix . 'cmdbsync`');
define('TABLE_BASEAPPLICATION',   '`' . $config->db->prefix . 'baseapplication`');
if(!defined('TABLE_NEED_DEAL_MESSAGE')) define('TABLE_NEED_DEAL_MESSAGE',  '`' . $config->db->prefix . 'need_deal_message`');
if(!defined('TABLE_MAIL_LOG')) define('TABLE_MAIL_LOG',  '`' . $config->db->prefix . 'mail_log`');
define('TABLE_CREDIT',   '`' . $config->db->prefix . 'credit`');
define('TABLE_LOCALESUPPORT',   '`' . $config->db->prefix . 'localesupport`'); //现场支持主表
define('TABLE_LOCALESUPPORT_WORKREPORT',   '`' . $config->db->prefix . 'localesupport_workreport`');  //现场支持报工表
define('TABLE_PROBLEM_CHANGE',   '`' . $config->db->prefix . 'problem_change`');
define('TABLE_ENVIRONMENTORDER', '`' . $config->db->prefix . 'environmentorder`');
define('TABLE_QUALITYGATE',   '`' . $config->db->prefix . 'qualitygate`');
define('TABLE_AUTHORITYAPPLY', '`' . $config->db->prefix . 'authorityapply`');
define('TABLE_THIRDPARTY_PRIVILEGE', '`' . $config->db->prefix . 'thirdparty_privilege`');
define('TABLE_THIRDPARTY_PRIVILEGE_URL', '`' . $config->db->prefix . 'thirdparty_privilege_url`');
define('TABLE_DATA_ACCESS', '`' . $config->db->prefix . 'data_access`');

if(!defined('TABLE_SYSTEM'))        define('TABLE_SYSTEM', '`' . $config->db->prefix . 'system`');
if(!defined('TABLE_SYSTEM_PARTITION'))        define('TABLE_SYSTEM_PARTITION', '`' . $config->db->prefix . 'system_partition`');


$config->objectTables['opinion']         = TABLE_OPINION;
$config->objectTables['opinioninside']   = TABLE_OPINIONINSIDE;
$config->objectTables['opinionchange']   = TABLE_OPINIONCHANGE;
$config->objectTables['requirement']     = TABLE_REQUIREMENT;
$config->objectTables['requirementinside']= TABLE_REQUIREMENTINSIDE;
$config->objectTables['requirementchangeoutside']= TABLE_REQUIREMENTCHANGEOUTSIDE;
$config->objectTables['application']     = TABLE_APPLICATION;
$config->objectTables['projectplan']     = TABLE_PROJECTPLAN;
$config->objectTables['outsideplan']     = TABLE_OUTSIDEPLAN;
$config->objectTables['problem']         = TABLE_PROBLEM;
$config->objectTables['demand']          = TABLE_DEMAND;
$config->objectTables['demand']          = TABLE_DEMANDINSIDE;
$config->objectTables['processimprove']  = TABLE_PROCESSIMPROVE;
$config->objectTables['info']            = TABLE_INFO;
$config->objectTables['duty']            = TABLE_DUTY;
$config->objectTables['modify']          = TABLE_MODIFY;
$config->objectTables['modifycncc']      = TABLE_MODIFYCNCC;
$config->objectTables['partition']       = TABLE_PARTITION;
$config->objectTables['change']          = TABLE_CHANGE;
$config->objectTables['infoqz']          = TABLE_INFO_QZ;
$config->objectTables['reviewmeeting']   = TABLE_REVIEW_MEETING;
$config->objectTables['residentsupport']   = TABLE_RESIDENT_SUPPORT_TEMPLATE_DEPT;
$config->objectTables['component']       = TABLE_COMPONENT;
$config->objectTables['outwarddelivery'] = TABLE_OUTWARDDELIVERY;
$config->objectTables['defect']          = TABLE_DEFECT;
$config->objectTables['datause']       = TABLE_DATAUSE;
$config->objectTables['toread']       = TABLE_TOREAD;
$config->objectTables['datamanagement']         = TABLE_DATAUSE;
$config->objectTables['secondorder']         = TABLE_SECONDORDER;
$config->objectTables['copyrightqz']         = TABLE_COPYRIGHTQZ;
$config->objectTables['copyright']         = TABLE_COPYRIGHT;
$config->objectTables['kanban']       = TABLE_KANBAN;
$config->objectTables['kanbanspace']  = TABLE_KANBANSPACE;
$config->objectTables['kanbanregion'] = TABLE_KANBANREGION;
$config->objectTables['kanbancolumn'] = TABLE_KANBANCOLUMN;
$config->objectTables['kanbanlane']   = TABLE_KANBANLANE;
$config->objectTables['kanbanorder']  = TABLE_KANBANORDER;
$config->objectTables['kanbangroup']  = TABLE_KANBANGROUP;
$config->objectTables['kanbancard']   = TABLE_KANBANCARD;
$config->objectTables['demandcollection']   = TABLE_DEMANDCOLLECTION;
$config->objectTables['sectransfer']   = TABLE_SECTRANSFER;
$config->objectTables['osspchange']    = TABLE_OSSPCHANGE;
$config->objectTables['closingitem']   = TABLE_CLOSINGITEM;
$config->objectTables['closingadvise'] = TABLE_CLOSINGADVISE;
$config->objectTables['authorization'] = TABLE_AUTHORIZATION;
$config->objectTables['putproduction'] = TABLE_PUTPRODUCTION;
$config->objectTables['credit']         = TABLE_CREDIT;
$config->objectTables['iwfp'] = TABLE_IWFP;
$config->objectTables['cmdbsync'] = TABLE_CMDBSYNC;
$config->objectTables['baseapplication'] = TABLE_BASEAPPLICATION;

$config->objectTables['zt_cmdbsync'] = TABLE_CMDBSYNC;
$config->objectTables['productionchange'] = TABLE_PRODUCTIONCHANGE;
$config->objectTables['problemchange'] = TABLE_PROBLEM_CHANGE;


$config->objectTables['localesupport'] = TABLE_LOCALESUPPORT;
$config->objectTables['localesupport_workreport'] = TABLE_LOCALESUPPORT_WORKREPORT;
$config->objectTables['deptorder']     = TABLE_DEPTORDER;

$config->objectTables['authorityapply']     = TABLE_AUTHORITYAPPLY;
$config->objectTables['thirdparty_privilege']     = TABLE_THIRDPARTY_PRIVILEGE;
$config->objectTables['thirdparty_privilege_url']     = TABLE_THIRDPARTY_PRIVILEGE_URL;
$config->objectTables['data_access']              = TABLE_DATA_ACCESS;
$config->objectTables['deptorder']     = TABLE_DEPTORDER;
$config->objectTables['qualitygate'] = TABLE_QUALITYGATE;
