<?php
$config->readonlyActions = array(); // 只读操作
$config->readonlyActions[] = 'apimeasure.getprojectreviewinfo';
$config->readonlyActions[] = 'apimeasure.getprojectunclosed';
$config->readonlyActions[] = 'apimeasure.getprojectworkloadbug';
$config->readonlyActions[] = 'apimeasure.getdeptconsumed';
$config->readonlyActions[] = 'apimeasure.getconsumedbyyear';
$config->readonlyActions[] = 'apimeasure.getconsumedtotaldetail';
$config->readonlyActions[] = 'apimeasure.getconsumedproject';
$config->readonlyActions[] = 'apimeasure.getconsumedprojectdetail';
$config->readonlyActions[] = 'apimeasure.getconsumedbasedetail';
$config->readonlyActions[] = 'apimeasure.getprojectsbyyear';
$config->readonlyActions[] = 'apimeasure.getDepartmentReviewStatistic';
$config->readonlyActions[] = 'apimeasure.getprojectreviewstatistic';
$config->readonlyActions[] = 'apimeasure.getprojectreviewdetails';
$config->readonlyActions[] = 'apimeasure.getprojectreviewdetailstotal';
$config->readonlyActions[] = 'apimeasure.getDepartmentRiskStatistic';
$config->readonlyActions[] = 'apimeasure.getProjectRiskStatistic';
$config->readonlyActions[] = 'apimeasure.getProjectRiskDetails';
$config->readonlyActions[] = 'apimeasure.getRiskMonthlyTrendData';
$config->readonlyActions[] = 'apimeasure.getalldepts';