<?php
$config->application = new stdclass();
$config->application->create = new stdclass();
$config->application->edit   = new stdclass();
$config->application->create->requiredFields = 'name,code,team,isPayment,isBasicLine,isSyncJinx,isSyncQz';
$config->application->edit->requiredFields = $config->application->create->requiredFields;

$config->application->editor = new stdclass();
$config->application->editor->create = array('id' => 'desc,comment,feature', 'tools' => 'simpleTools');
$config->application->editor->edit   = array('id' => 'desc,comment,feature', 'tools' => 'simpleTools');
$config->application->editor->view   = array('id' => 'desc,comment,feature', 'tools' => 'simpleTools');

$config->application->list = new stdclass();
//$config->application->list->exportFields = 'id,name,code,team,isBasicLine,isSyncJinx,isSyncQz,isPayment,attribute,network,fromUnit,belongDeptIds,version,feature,range,useDept,projectMonth,productDate,opsDate,promote,protectLevel,continueLevel,securityLevel,cityBak,offsiteBak,vendor,vendorContact,retrofit,runStatus,runUnit,runLeader,runDept,owner,opsLeader,opsDept,opsManager,info,desc';
$config->application->list->exportFields = 'id,name,code,isPayment,team,fromUnit,belongOrganization,securityLevel,attribute,isBasicLine,baselineSystem,isSyncJinx,isSyncQz,vendor,vendorContact,systemManager,systemDept,createdBy,createdDate,desc,feature,continueLevel,protectLevel,range,projectMonth,network,architecture,userScope,recoveryStrategy,version,productDate,opsDate,promote,cityBak,offsiteBak,retrofit,runStatus,runUnit,runDept,owner,opsDept,opsManager,serviceTime,facilitiesStatus,resourceLocat';

$config->application->export = new stdclass();
$config->application->export->templateFields = explode(',',"name,code,team,isPayment,attribute,network,fromUnit,continueLevel,feature,range,useDept,projectMonth,productDate,desc,isBasicLine,isSyncJinx,isSyncQz");
$config->application->export->listFields = explode(',',"team,isBasicLine,isSyncJinx,isSyncQz,isPayment,attribute,network,fromUnit,continueLevel");

/* Search. */
global $lang;
$config->application->search['module']                      = 'application';
$config->application->search['fields']                         = array();
$config->application->search['fields']['code']              = $lang->application->code;
$config->application->search['fields']['name']             = $lang->application->name;
$config->application->search['fields']['isBasicLine']             = $lang->application->isBasicLine;
$config->application->search['fields']['isSyncJinx']             = $lang->application->isSyncJinx;
$config->application->search['fields']['isSyncQz']             = $lang->application->isSyncQz;
$config->application->search['fields']['team']              = $lang->application->team;
$config->application->search['fields']['isPayment']      = $lang->application->isPayment;
$config->application->search['fields']['attribute']         = $lang->application->attribute;
$config->application->search['fields']['network']          = $lang->application->network;
$config->application->search['fields']['fromUnit']         = $lang->application->fromUnit;
$config->application->search['fields']['version']           = $lang->application->version;
$config->application->search['fields']['feature']           = $lang->application->feature;
$config->application->search['fields']['range']             = $lang->application->range;
$config->application->search['fields']['useDept']         = $lang->application->useDept;
$config->application->search['fields']['projectMonth']  = $lang->application->projectMonth;
$config->application->search['fields']['productDate']   = $lang->application->productDate;
$config->application->search['fields']['opsDate']         = $lang->application->opsDate;
$config->application->search['fields']['promote']         = $lang->application->promote;
$config->application->search['fields']['protectLevel']   = $lang->application->protectLevel;
$config->application->search['fields']['continueLevel'] = $lang->application->continueLevel;
$config->application->search['fields']['securityLevel']  = $lang->application->securityLevel;
$config->application->search['fields']['cityBak']          = $lang->application->cityBak;
$config->application->search['fields']['offsiteBak']      = $lang->application->offsiteBak;
$config->application->search['fields']['vendor']           = $lang->application->vendor;
$config->application->search['fields']['vendorContact'] = $lang->application->vendorContact;
$config->application->search['fields']['retrofit']           = $lang->application->retrofit;
$config->application->search['fields']['runStatus']       = $lang->application->runStatus;
$config->application->search['fields']['runUnit']           = $lang->application->runUnit;
$config->application->search['fields']['runLeader']       = $lang->application->runLeader;
$config->application->search['fields']['runDept']          = $lang->application->runDept;
$config->application->search['fields']['owner']             = $lang->application->owner;
$config->application->search['fields']['opsLeader']      = $lang->application->opsLeader;
$config->application->search['fields']['opsDept']         = $lang->application->opsDept;
$config->application->search['fields']['desc']              = $lang->application->desc;
$config->application->search['fields']['createdDate']   = $lang->application->createdDate;
$config->application->search['fields']['createdBy']       = $lang->application->createdBy;
$config->application->search['fields']['editedDate']     = $lang->application->editedDate;
$config->application->search['fields']['editedBy']         = $lang->application->editedBy;

$config->application->search['params']['code'] = array('operator' => 'include', 'control' => 'input', 'values' => '');
$config->application->search['params']['name'] = array('operator' => 'include', 'control' => 'input',  'values' => '');
$config->application->search['params']['isBasicLine'] = array('operator' => '=', 'control' => 'select',  'values' => $lang->application->boolList);
$config->application->search['params']['isSyncJinx'] = array('operator' => '=', 'control' => 'select',  'values' => $lang->application->boolList);
$config->application->search['params']['isSyncQz'] = array('operator' => '=', 'control' => 'select',  'values' => $lang->application->boolList);
$config->application->search['params']['team']              = array('operator' => '=', 'control' => 'select',  'values' => $lang->application->teamList);
$config->application->search['params']['isPayment']      = array('operator' => '=', 'control' => 'select',  'values' => $lang->application->isPaymentList);
$config->application->search['params']['attribute']         = array('operator' => '=', 'control' => 'select',  'values' => $lang->application->attributeList);
$config->application->search['params']['network']          = array('operator' => '=', 'control' => 'select',  'values' => $lang->application->networkList);
$config->application->search['params']['fromUnit']         = array('operator' => '=', 'control' => 'select',  'values' => $lang->application->fromUnitList);
$config->application->search['params']['version']           = array('operator' => 'include', 'control' => 'input',  'values' => '');
$config->application->search['params']['feature']           = array('operator' => 'include', 'control' => 'input',  'values' => '');
$config->application->search['params']['range']             = array('operator' => 'include', 'control' => 'input',  'values' => '');
$config->application->search['params']['useDept']         = array('operator' => 'include', 'control' => 'input',  'values' => '');
$config->application->search['params']['projectMonth']  = array('operator' => 'include', 'control' => 'input',  'values' => '');
$config->application->search['params']['productDate']   = array('operator' => '=', 'control' => 'input', 'class' => 'date',  'values' => '');
$config->application->search['params']['opsDate']         = array('operator' => '=', 'control' => 'input', 'class' => 'date',  'values' => '');
$config->application->search['params']['promote']         = array('operator' => 'include', 'control' => 'input',  'values' => '');
$config->application->search['params']['protectLevel']   = array('operator' => 'include', 'control' => 'input',  'values' => '');
$config->application->search['params']['continueLevel'] = array('operator' => 'include', 'control' => 'select',  'values' => $lang->application->continueLevelList);
$config->application->search['params']['securityLevel']  = array('operator' => 'include', 'control' => 'input',  'values' => '');
$config->application->search['params']['cityBak']          = array('operator' => 'include', 'control' => 'input',  'values' => '');
$config->application->search['params']['offsiteBak']      = array('operator' => 'include', 'control' => 'input',  'values' => '');
$config->application->search['params']['vendor']           = array('operator' => 'include', 'control' => 'input',  'values' => '');
$config->application->search['params']['vendorContact'] = array('operator' => 'include', 'control' => 'input',  'values' => '');
$config->application->search['params']['retrofit']           = array('operator' => 'include', 'control' => 'input',  'values' => '');
$config->application->search['params']['runStatus']       = array('operator' => '=', 'control' => 'select',  'values' => $lang->application->runStatusList);
$config->application->search['params']['runUnit']           = array('operator' => 'include', 'control' => 'input',  'values' => '');
$config->application->search['params']['runLeader']       = array('operator' => 'include', 'control' => 'input',  'values' => '');
$config->application->search['params']['runDept']          = array('operator' => 'include', 'control' => 'input',  'values' => '');
$config->application->search['params']['owner']             = array('operator' => 'include', 'control' => 'input',  'values' => '');
$config->application->search['params']['opsLeader']      = array('operator' => 'include', 'control' => 'input',  'values' => '');
$config->application->search['params']['opsDept']         = array('operator' => 'include', 'control' => 'input',  'values' => '');
$config->application->search['params']['opsManager']   = array('operator' => 'include', 'control' => 'input',  'values' => '');
$config->application->search['params']['desc']              = array('operator' => 'include', 'control' => 'input', 'values' => '');
$config->application->search['params']['createdBy']      = array('operator' => 'include', 'control' => 'input', 'values' => '');
$config->application->search['params']['createdDate']   = array('operator' => '=', 'control' => 'input', 'class' => 'date',  'values' => '');
$config->application->search['params']['editedBy']        = array('operator' => 'include', 'control' => 'input', 'values' => '');
$config->application->search['params']['editedDate']    = array('operator' => '=', 'control' => 'input', 'class' => 'date',  'values' => '');

