
-- ----------------------------
-- 2022-11-28  liuyuhan 新增和修改记录
-- ----------------------------
UPDATE zt_partition SET name = 'SMIVSAPB', application = 'MIVS', ip = '11.194.0.221', applicationName = 'MIVS', dataOrigin = 1, deleted = 1, deletedDate = '2022-11-28' WHERE id = 4518;
UPDATE zt_partition SET name = 'W0105GWA01', application = 'EAP', ip = '11.195.86.192', applicationName = 'EAP', dataOrigin = 1, deleted = 1, deletedDate = '2022-11-28' WHERE id = 3436;
UPDATE zt_partition SET name = 'W0301GWA01', application = 'EAP', ip = '11.195.86.196', applicationName = 'EAP', dataOrigin = 1, deleted = 1, deletedDate = '2022-11-28' WHERE id = 3438;
UPDATE zt_partition SET name = 'W0301GWA02', application = 'EAP', ip = '11.195.86.197', applicationName = 'EAP', dataOrigin = 1, deleted = 1, deletedDate = '2022-11-28' WHERE id = 3439;
UPDATE zt_partition SET name = 'WPMTSAPF', application = 'PMTSNPC', ip = '11.195.0.91', applicationName = 'PMTSNPC', dataOrigin = 1, deleted = 1, deletedDate = '2022-11-28' WHERE id = 5174;
UPDATE zt_partition SET name = 'WPMTSAPE', application = 'PMTSNPC', ip = '11.195.0.85', applicationName = 'PMTSNPC', dataOrigin = 1, deleted = 1, deletedDate = '2022-11-28' WHERE id = 5173;
UPDATE zt_partition SET name = 'WPMTSAPB', application = 'PMTSNPC', ip = '11.195.0.214', applicationName = 'PMTSNPC', dataOrigin = 1, deleted = 1, deletedDate = '2022-11-28' WHERE id = 5172;
UPDATE zt_partition SET name = 'WPMTSAPA', application = 'PMTSNPC', ip = '11.195.0.213', applicationName = 'PMTSNPC', dataOrigin = 1, deleted = 1, deletedDate = '2022-11-28' WHERE id = 5171;
UPDATE zt_partition SET name = 'WPMTSAPD', application = 'PMTSNPC', ip = '11.195.0.211', applicationName = 'PMTSNPC', dataOrigin = 1, deleted = 1, deletedDate = '2022-11-28' WHERE id = 5170;
UPDATE zt_partition SET name = 'WPMTSAPC', application = 'PMTSNPC', ip = '11.195.0.209', applicationName = 'PMTSNPC', dataOrigin = 1, deleted = 1, deletedDate = '2022-11-28' WHERE id = 5169;
UPDATE zt_partition SET name = 'W0105GWA02', application = 'EAP', ip = '11.195.86.193', applicationName = 'EAP', dataOrigin = 1, deleted = 1, deletedDate = '2022-11-28' WHERE id = 3437;
UPDATE zt_partition SET name = 'SMIVSAPD', application = 'MIVS', ip = '11.194.0.223', applicationName = 'MIVS', dataOrigin = 1, deleted = 1, deletedDate = '2022-11-28' WHERE id = 4520;
UPDATE zt_partition SET name = 'WNPFEA01', application = 'NPFE/NIFE', ip = '11.195.80.16', applicationName = 'NPFE/NIFE', dataOrigin = 1, deleted = 1, deletedDate = '2022-11-28' WHERE id = 4887;
UPDATE zt_partition SET name = 'WNPFEA02', application = 'NPFE/NIFE', ip = '11.195.80.17', applicationName = 'NPFE/NIFE', dataOrigin = 1, deleted = 1, deletedDate = '2022-11-28' WHERE id = 4888;
UPDATE zt_partition SET name = 'WNPFEB01', application = 'NPFE/NIFE', ip = '11.195.80.18', applicationName = 'NPFE/NIFE', dataOrigin = 1, deleted = 1, deletedDate = '2022-11-28' WHERE id = 4889;
UPDATE zt_partition SET name = 'WNPFEB02', application = 'NPFE/NIFE', ip = '11.195.80.19', applicationName = 'NPFE/NIFE', dataOrigin = 1, deleted = 1, deletedDate = '2022-11-28' WHERE id = 4890;
UPDATE zt_partition SET name = 'SPMISWB1', application = 'PMIS', ip = '11.194.56.4', applicationName = 'PMIS', dataOrigin = 1, deleted = 1, deletedDate = '2022-11-28' WHERE id = 4999;
UPDATE zt_partition SET name = 'SPMISWB2', application = 'PMIS', ip = '11.194.56.5', applicationName = 'PMIS', dataOrigin = 1, deleted = 1, deletedDate = '2022-11-28' WHERE id = 5000;
UPDATE zt_partition SET name = 'SPMISWB3', application = 'PMIS', ip = '11.194.56.6', applicationName = 'PMIS', dataOrigin = 1, deleted = 1, deletedDate = '2022-11-28' WHERE id = 5001;
UPDATE zt_partition SET name = 'SPMISWB4', application = 'PMIS', ip = '11.194.56.7', applicationName = 'PMIS', dataOrigin = 1, deleted = 1, deletedDate = '2022-11-28' WHERE id = 5002;
UPDATE zt_partition SET name = 'S9301GWB01', application = 'EAP', ip = '11.194.86.198', applicationName = 'EAP', dataOrigin = 1, deleted = 1, deletedDate = '2022-11-28' WHERE id = 3433;
UPDATE zt_partition SET name = 'SCBSPAD9A', application = 'CBSPAD', ip = '17.194.128.9', applicationName = 'CBSPAD', dataOrigin = 1, deleted = 1, deletedDate = '2022-11-28' WHERE id = 2999;
UPDATE zt_partition SET name = 'SCBSPAD9B', application = 'CBSPAD', ip = '17.194.144.9', applicationName = 'CBSPAD', dataOrigin = 1, deleted = 1, deletedDate = '2022-11-28' WHERE id = 3011;
UPDATE zt_partition SET name = 'S9989GWB01', application = 'CIPSFE', ip = '11.194.86.212', applicationName = 'CIPSFE', dataOrigin = 1, deleted = 1, deletedDate = '2022-11-28' WHERE id = 3171;
UPDATE zt_partition SET name = 'S9989GWB02', application = 'CIPSFE', ip = '11.194.86.213', applicationName = 'CIPSFE', dataOrigin = 1, deleted = 1, deletedDate = '2022-11-28' WHERE id = 3172;
UPDATE zt_partition SET name = 'S9102GWB01', application = 'EAP', ip = '11.194.86.182', applicationName = 'EAP', dataOrigin = 1, deleted = 1, deletedDate = '2022-11-28' WHERE id = 3418;
UPDATE zt_partition SET name = 'S9102GWB02', application = 'EAP', ip = '11.194.86.183', applicationName = 'EAP', dataOrigin = 1, deleted = 1, deletedDate = '2022-11-28' WHERE id = 3419;
UPDATE zt_partition SET name = 'S9103GWB01', application = 'EAP', ip = '11.194.86.186', applicationName = 'EAP', dataOrigin = 1, deleted = 1, deletedDate = '2022-11-28' WHERE id = 3422;
UPDATE zt_partition SET name = 'S9103GWB02', application = 'EAP', ip = '11.194.86.187', applicationName = 'EAP', dataOrigin = 1, deleted = 1, deletedDate = '2022-11-28' WHERE id = 3423;
UPDATE zt_partition SET name = 'S9104GWB01', application = 'EAP', ip = '11.194.86.190', applicationName = 'EAP', dataOrigin = 1, deleted = 1, deletedDate = '2022-11-28' WHERE id = 3426;
UPDATE zt_partition SET name = 'S9104GWB02', application = 'EAP', ip = '11.194.86.191', applicationName = 'EAP', dataOrigin = 1, deleted = 1, deletedDate = '2022-11-28' WHERE id = 3427;
UPDATE zt_partition SET name = 'S9105GWB01', application = 'EAP', ip = '11.194.86.194', applicationName = 'EAP', dataOrigin = 1, deleted = 1, deletedDate = '2022-11-28' WHERE id = 3430;
UPDATE zt_partition SET name = 'S9105GWB02', application = 'EAP', ip = '11.194.86.195', applicationName = 'EAP', dataOrigin = 1, deleted = 1, deletedDate = '2022-11-28' WHERE id = 3431;
UPDATE zt_partition SET name = 'S9301GWB02', application = 'EAP', ip = '11.194.86.199', applicationName = 'EAP', dataOrigin = 1, deleted = 1, deletedDate = '2022-11-28' WHERE id = 3434;
UPDATE zt_partition SET name = 'BTDBDG02', application = 'DBRG', ip = '17.192.109.163', applicationName = 'DBRG', dataOrigin = 1, deleted = 0, deletedDate = null WHERE id = 5197;
UPDATE zt_partition SET name = 'BTDBDG03', application = 'DBRG', ip = '17.192.109.164', applicationName = 'DBRG', dataOrigin = 1, deleted = 0, deletedDate = null WHERE id = 5198;
UPDATE zt_partition SET name = 'BTDBDG01', application = 'DBRG', ip = '17.192.77.163', applicationName = 'DBRG', dataOrigin = 1, deleted = 0, deletedDate = null WHERE id = 5208;
UPDATE zt_partition SET name = 'STDBDG01', application = 'DBRG', ip = '17.194.131.5', applicationName = 'DBRG', dataOrigin = 1, deleted = 0, deletedDate = null WHERE id = 5219;
UPDATE zt_partition SET name = 'X3650-M3-II', application = 'MF', ip = '11.195.13.56', applicationName = 'MF', dataOrigin = null, deleted = 0, deletedDate = null WHERE id = 4481;
UPDATE zt_partition SET name = 'STDBDG02', application = 'DBRG', ip = '17.194.147.5', applicationName = 'DBRG', dataOrigin = 1, deleted = 0, deletedDate = null WHERE id = 5230;
UPDATE zt_partition SET name = 'STDBDG03', application = 'DBRG', ip = '17.194.147.6', applicationName = 'DBRG', dataOrigin = 1, deleted = 0, deletedDate = null WHERE id = 5231;
UPDATE zt_partition SET name = 'WTDBDG01', application = 'DBRG', ip = '17.195.131.5', applicationName = 'DBRG', dataOrigin = 1, deleted = 0, deletedDate = null WHERE id = 5240;
UPDATE zt_partition SET name = 'WTDBDG02', application = 'DBRG', ip = '17.195.147.5', applicationName = 'DBRG', dataOrigin = 1, deleted = 0, deletedDate = null WHERE id = 5251;
UPDATE zt_partition SET name = 'WTDBDG03', application = 'DBRG', ip = '17.195.147.6', applicationName = 'DBRG', dataOrigin = 1, deleted = 0, deletedDate = null WHERE id = 5252;
UPDATE zt_partition SET name = 'BJN-OMP-MFITM3', application = 'MF', ip = '17.192.6.3', applicationName = 'MF', dataOrigin = null, deleted = 0, deletedDate = null WHERE id = 4493;
UPDATE zt_partition SET name = 'BJN-OMP-MFITM2', application = 'MF', ip = '17.192.6.2', applicationName = 'MF', dataOrigin = null, deleted = 0, deletedDate = null WHERE id = 4492;
UPDATE zt_partition SET name = 'BJN-OMP-MFITM1', application = 'MF', ip = '17.192.6.1', applicationName = 'MF', dataOrigin = null, deleted = 0, deletedDate = null WHERE id = 4491;
UPDATE zt_partition SET name = 'X3650-M3', application = 'MF', ip = '11.195.13.57', applicationName = 'MF', dataOrigin = null, deleted = 0, deletedDate = null WHERE id = 4482;
UPDATE zt_partition SET name = 'CCPC_SYS', application = 'CCPCSYS', ip = '255.255.255.1', applicationName = 'CCPCSYS', dataOrigin = 2, deleted = 0, deletedDate = null WHERE id = 2334;
UPDATE zt_partition SET name = 'MF-Monitor', application = 'MF', ip = '11.195.13.55', applicationName = 'MF', dataOrigin = null, deleted = 0, deletedDate = null WHERE id = 4480;
UPDATE zt_partition SET name = 'SB_X3650_13', application = 'MF', ip = '11.194.13.57', applicationName = 'MF', dataOrigin = null, deleted = 0, deletedDate = null WHERE id = 4476;
UPDATE zt_partition SET name = 'SB_X3650_14', application = 'MF', ip = '11.194.13.56', applicationName = 'MF', dataOrigin = null, deleted = 0, deletedDate = null WHERE id = 4475;
UPDATE zt_partition SET name = 'SB_X3650_12', application = 'MF', ip = '11.194.13.55', applicationName = 'MF', dataOrigin = null, deleted = 0, deletedDate = null WHERE id = 4474;
UPDATE zt_partition SET name = 'W0989GWA01', application = 'CIPSFE', ip = '17.195.209.48', applicationName = 'CIPSFE', dataOrigin = 1, deleted = 0, deletedDate = null WHERE id = 3175;
UPDATE zt_partition SET name = 'SCFMSAPB', application = 'CFMS', ip = '17.194.147.35', applicationName = 'CFMS', dataOrigin = 1, deleted = 0, deletedDate = null WHERE id = 2813;
UPDATE zt_partition SET name = 'SCFMSAPA', application = 'CFMS', ip = '17.194.131.35', applicationName = 'CFMS', dataOrigin = 1, deleted = 0, deletedDate = null WHERE id = 2810;
UPDATE zt_partition SET name = 'bjncsmprdb', application = 'Tivoli', ip = '31.192.82.75', applicationName = 'Tivoli', dataOrigin = 1, deleted = 0, deletedDate = null WHERE id = 2337;
UPDATE zt_partition SET name = 'bjncsmproc', application = 'Tivoli', ip = '31.192.82.74', applicationName = 'Tivoli', dataOrigin = 1, deleted = 0, deletedDate = null WHERE id = 2336;
UPDATE zt_partition SET name = 'DEPX', application = 'DEPX', ip = '255.255.255.255', applicationName = 'DEPX', dataOrigin = 1, deleted = 0, deletedDate = null WHERE id = 2335;
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('BCAOSSWA', 'CAOS', '17.192.76.171', 'CAOS', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('BCAOSSWB', 'CAOS', '17.192.108.171', 'CAOS', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('BCAOSSWC', 'CAOS', '17.192.108.172', 'CAOS', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('BCOWSAPC', 'COWS', '17.192.76.170', 'COWS', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('BCOWSAPD', 'COWS', '17.192.108.170', 'COWS', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('BJBDPES14', 'FBDASP', '17.192.225.31', 'FBDASP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('BJBDPES15', 'FBDASP', '17.192.225.32', 'FBDASP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('BJBDPES16', 'FBDASP', '17.192.225.33', 'FBDASP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('BJBDPES17', 'FBDASP', '17.192.225.34', 'FBDASP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('BJBDPES18', 'FBDASP', '17.192.225.35', 'FBDASP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('BJBDPES19', 'FBDASP', '17.192.225.36', 'FBDASP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('BJBDPFL05', 'FBDASP', '17.192.225.37', 'FBDASP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('BJBDPFL06', 'FBDASP', '17.192.225.38', 'FBDASP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('BJBDPFL07', 'FBDASP', '17.192.225.39', 'FBDASP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('BJBDPFL08', 'FBDASP', '17.192.225.40', 'FBDASP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('BJBDPFL09', 'FBDASP', '17.192.225.41', 'FBDASP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('BJN-SMP-HIDS', 'HIDS', '17.192.3.130', 'HIDS', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('BJOSSEC01', 'FBDASP', '17.192.225.75', 'FBDASP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('BJOSSEC02', 'FBDASP', '17.192.225.82', 'FBDASP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('BJOSSEC03', 'FBDASP', '17.192.225.89', 'FBDASP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('BJOSSEC04', 'FBDASP', '17.192.225.76', 'FBDASP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('BJOSSEC05', 'FBDASP', '17.192.225.83', 'FBDASP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('BJOSSEC06', 'FBDASP', '17.192.225.90', 'FBDASP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('BJOSSEC07', 'FBDASP', '17.192.225.77', 'FBDASP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('BJOSSEC08', 'FBDASP', '17.192.225.84', 'FBDASP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('BJOSSEC09', 'FBDASP', '17.192.225.91', 'FBDASP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('BJOSSEC10', 'FBDASP', '17.192.225.78', 'FBDASP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('BJOSSEC11', 'FBDASP', '17.192.225.85', 'FBDASP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('BJOSSTN01', 'FBDASP', '17.192.225.72', 'FBDASP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('BJOSSTN02', 'FBDASP', '17.192.225.79', 'FBDASP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('BJOSSTN03', 'FBDASP', '17.192.225.86', 'FBDASP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('BJOSSTN04', 'FBDASP', '17.192.225.73', 'FBDASP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('BJOSSTN05', 'FBDASP', '17.192.225.80', 'FBDASP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('BJOSSTN06', 'FBDASP', '17.192.225.87', 'FBDASP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('BJOSSTN07', 'FBDASP', '17.192.225.74', 'FBDASP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('BJOSSTN08', 'FBDASP', '17.192.225.81', 'FBDASP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('BJOSSTN09', 'FBDASP', '17.192.225.88', 'FBDASP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('BMMPABCN01', 'MPP', '17.192.225.43', 'MPP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('BMMPABCN02', 'MPP', '17.192.225.53', 'MPP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('BMMPABCN03', 'MPP', '17.192.225.63', 'MPP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('BMMPSBCN01', 'MPP', '17.192.225.50', 'MPP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('BMMPSBCN02', 'MPP', '17.192.225.60', 'MPP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('BMMPSBCN03', 'MPP', '17.192.225.70', 'MPP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('BMMPSBCN04', 'MPP', '17.192.225.48', 'MPP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('BMMPSBCN05', 'MPP', '17.192.225.58', 'MPP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('BMMPSBCN06', 'MPP', '17.192.225.68', 'MPP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('BMMPSBDN07', 'MPP', '17.192.225.49', 'MPP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('BMMPSBDN08', 'MPP', '17.192.225.59', 'MPP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('BMMPSBDN09', 'MPP', '17.192.225.69', 'MPP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('BMMPSBDN10', 'MPP', '17.192.225.51', 'MPP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('BMMPSBDN11', 'MPP', '17.192.225.61', 'MPP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('BMMPSBDN12', 'MPP', '17.192.225.71', 'MPP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('BMNGSSLA', 'NetSign', '17.192.62.164', 'NetSign', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('BMNGSSLB', 'NetSign', '17.192.124.164', 'NetSign', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('BSMPABCN01', 'MPP', '17.192.225.42', 'MPP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('BSMPABCN02', 'MPP', '17.192.225.52', 'MPP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('BSMPABCN03', 'MPP', '17.192.225.62', 'MPP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('BSMPSBCN01', 'MPP', '17.192.225.46', 'MPP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('BSMPSBCN02', 'MPP', '17.192.225.56', 'MPP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('BSMPSBCN03', 'MPP', '17.192.225.66', 'MPP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('BSMPSBCN04', 'MPP', '17.192.225.44', 'MPP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('BSMPSBCN05', 'MPP', '17.192.225.54', 'MPP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('BSMPSBCN06', 'MPP', '17.192.225.64', 'MPP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('BSMPSBDN07', 'MPP', '17.192.225.45', 'MPP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('BSMPSBDN08', 'MPP', '17.192.225.55', 'MPP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('BSMPSBDN09', 'MPP', '17.192.225.65', 'MPP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('BSMPSBDN10', 'MPP', '17.192.225.47', 'MPP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('BSMPSBDN11', 'MPP', '17.192.225.57', 'MPP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('BSMPSBDN12', 'MPP', '17.192.225.67', 'MPP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('BTDBDG04', 'DBRG', '17.192.77.187', 'DBRG', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('BTDBDG05', 'DBRG', '17.192.109.187', 'DBRG', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('BTDBDG06', 'DBRG', '17.192.109.188', 'DBRG', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('S9102GWA01_NEW', 'EAP', '17.194.209.16', 'EAP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('S9102GWA02_NEW', 'EAP', '17.194.209.17', 'EAP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('S9102GWB01_NEW', 'EAP', '17.194.209.18', 'EAP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('S9102GWB02_NEW', 'EAP', '17.194.209.19', 'EAP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('S9103GWB01', 'EAP', '17.194.209.22', 'EAP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('S9103GWB02_NEW', 'EAP', '17.192.209.23', 'EAP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('S9104GWB01_NEW', 'EAP', '17.194.209.26', 'EAP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('S9104GWB02_NEW', 'EAP', '17.194.209.27', 'EAP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('S9105GWB01_NEW', 'EAP', '17.194.209.30', 'EAP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('S9105GWB02_NEW', 'EAP', '17.194.209.31', 'EAP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('S9301GWB01_NEW', 'EAP', '17.194.209.34', 'EAP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('S9301GWB02_NEW', 'EAP', '17.194.209.35', 'EAP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('S9989GWA01_NEW', 'CIPSFE', '17.194.209.48', 'CIPSFE', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('S9989GWA02_NEW', 'CIPSFE', '17.194.209.49', 'CIPSFE', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('S9989GWB01_NEW', 'CIPSFE', '17.194.209.50', 'CIPSFE', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('S9989GWB02_NEW', 'CIPSFE', '17.194.209.51', 'CIPSFE', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('SCOWSAPC', 'COWS', '17.194.140.8', 'COWS', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('SCOWSAPD', 'COWS', '17.194.156.8', 'COWS', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('SHBDPES14', 'FBDASP', '17.194.226.1', 'FBDASP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('SHBDPES15', 'FBDASP', '17.194.226.2', 'FBDASP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('SHBDPES16', 'FBDASP', '17.194.226.3', 'FBDASP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('SHBDPES17', 'FBDASP', '17.194.226.4', 'FBDASP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('SHBDPES18', 'FBDASP', '17.194.226.5', 'FBDASP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('SHBDPES19', 'FBDASP', '17.194.226.6', 'FBDASP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('SHBDPFL05', 'FBDASP', '17.194.226.7', 'FBDASP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('SHBDPFL06', 'FBDASP', '17.194.226.8', 'FBDASP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('SHBDPFL07', 'FBDASP', '17.194.226.9', 'FBDASP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('SHBDPFL08', 'FBDASP', '17.194.226.10', 'FBDASP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('SHBDPFL09', 'FBDASP', '17.194.226.11', 'FBDASP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('SHOSSEC01', 'FBDASP', '17.194.226.75', 'FBDASP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('SHOSSEC02', 'FBDASP', '17.194.226.82', 'FBDASP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('SHOSSEC03', 'FBDASP', '17.194.226.89', 'FBDASP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('SHOSSEC04', 'FBDASP', '17.194.226.76', 'FBDASP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('SHOSSEC05', 'FBDASP', '17.194.226.83', 'FBDASP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('SHOSSEC06', 'FBDASP', '17.194.226.90', 'FBDASP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('SHOSSEC07', 'FBDASP', '17.194.226.77', 'FBDASP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('SHOSSEC08', 'FBDASP', '17.194.226.84', 'FBDASP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('SHOSSEC09', 'FBDASP', '17.194.226.91', 'FBDASP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('SHOSSEC10', 'FBDASP', '17.194.226.78', 'FBDASP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('SHOSSEC11', 'FBDASP', '17.194.226.85', 'FBDASP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('SHOSSTN01', 'FBDASP', '17.194.226.72', 'FBDASP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('SHOSSTN02', 'FBDASP', '17.194.226.79', 'FBDASP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('SHOSSTN03', 'FBDASP', '17.194.226.86', 'FBDASP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('SHOSSTN04', 'FBDASP', '17.194.226.73', 'FBDASP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('SHOSSTN05', 'FBDASP', '17.194.226.80', 'FBDASP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('SHOSSTN06', 'FBDASP', '17.194.226.87', 'FBDASP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('SHOSSTN07', 'FBDASP', '17.194.226.74', 'FBDASP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('SHOSSTN08', 'FBDASP', '17.194.226.81', 'FBDASP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('SHOSSTN09', 'FBDASP', '17.194.226.88', 'FBDASP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('SMIVSAPA_V43', 'MIVS', '17.194.201.16', 'MIVS', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('SMIVSAPB_V43', 'MIVS', '17.194.203.17', 'MIVS', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('SMIVSAPC_V43', 'MIVS', '17.194.201.18', 'MIVS', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('SMIVSAPD_V43', 'MIVS', '17.194.203.19', 'MIVS', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('SMMPAACN01', 'MPP', '17.194.226.39', 'MPP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('SMMPAACN02', 'MPP', '17.194.226.18', 'MPP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('SMMPAACN03', 'MPP', '17.194.226.33', 'MPP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('SMMPAADN04', 'MPP', '17.194.226.19', 'MPP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('SMMPAADN05', 'MPP', '17.194.226.26', 'MPP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('SMMPAADN06', 'MPP', '17.194.226.27', 'MPP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('SMMPAADN07', 'MPP', '17.194.226.34', 'MPP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('SMMPAADN08', 'MPP', '17.194.226.40', 'MPP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('SMMPAADN09', 'MPP', '17.194.226.41', 'MPP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('SMMPABCN01', 'MPP', '17.194.226.17', 'MPP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('SMMPABCN02', 'MPP', '17.194.226.25', 'MPP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('SMMPABCN03', 'MPP', '17.194.226.32', 'MPP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('SMMPSACN01', 'MPP', '17.194.226.24', 'MPP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('SMMPSACN02', 'MPP', '17.194.226.30', 'MPP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('SMMPSACN03', 'MPP', '17.194.226.36', 'MPP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('SMMPSADN04', 'MPP', '17.194.226.37', 'MPP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('SMMPSADN05', 'MPP', '17.194.226.38', 'MPP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('SMMPSADN06', 'MPP', '17.194.226.31', 'MPP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('SMMPSBCN01', 'MPP', '17.194.226.28', 'MPP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('SMMPSBCN02', 'MPP', '17.194.226.20', 'MPP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('SMMPSBCN03', 'MPP', '17.194.226.21', 'MPP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('SMMPSBCN04', 'MPP', '17.194.226.12', 'MPP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('SMMPSBCN05', 'MPP', '17.194.226.13', 'MPP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('SMMPSBDN06', 'MPP', '17.194.226.14', 'MPP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('SMMPSBDN07', 'MPP', '17.194.226.15', 'MPP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('SMMPSBDN08', 'MPP', '17.194.226.16', 'MPP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('SMMPSBDN09', 'MPP', '17.194.226.29', 'MPP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('SMMPSBDN10', 'MPP', '17.194.226.22', 'MPP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('SMMPSBDN11', 'MPP', '17.194.226.23', 'MPP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('SMMPSBDN12', 'MPP', '17.194.226.35', 'MPP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('SMPPMN01', 'MPP', '17.194.140.12', 'MPP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('SMPPMN02', 'MPP', '17.194.156.12', 'MPP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('SMPPMN03', 'MPP', '17.194.156.13', 'MPP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('SNPFED01_NEW', 'NPFE/NIFE', '17.194.209.7', 'NPFE/NIFE', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('SNPFED02_NEW', 'NPFE/NIFE', '17.194.209.8', 'NPFE/NIFE', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('SSMPAACN01', 'MPP', '17.194.226.69', 'MPP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('SSMPAACN02', 'MPP', '17.194.226.48', 'MPP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('SSMPAACN03', 'MPP', '17.194.226.63', 'MPP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('SSMPAADN04', 'MPP', '17.194.226.49', 'MPP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('SSMPAADN05', 'MPP', '17.194.226.56', 'MPP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('SSMPAADN06', 'MPP', '17.194.226.57', 'MPP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('SSMPAADN07', 'MPP', '17.194.226.64', 'MPP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('SSMPAADN08', 'MPP', '17.194.226.70', 'MPP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('SSMPAADN09', 'MPP', '17.194.226.71', 'MPP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('SSMPABCN01', 'MPP', '17.194.226.47', 'MPP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('SSMPABCN02', 'MPP', '17.194.226.55', 'MPP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('SSMPABCN03', 'MPP', '17.194.226.62', 'MPP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('SSMPSACN01', 'MPP', '17.194.226.54', 'MPP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('SSMPSACN02', 'MPP', '17.194.226.60', 'MPP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('SSMPSACN03', 'MPP', '17.194.226.66', 'MPP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('SSMPSADN04', 'MPP', '17.194.226.67', 'MPP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('SSMPSADN05', 'MPP', '17.194.226.68', 'MPP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('SSMPSADN06', 'MPP', '17.194.226.61', 'MPP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('SSMPSBCN01', 'MPP', '17.194.226.58', 'MPP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('SSMPSBCN02', 'MPP', '17.194.226.50', 'MPP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('SSMPSBCN03', 'MPP', '17.194.226.51', 'MPP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('SSMPSBCN04', 'MPP', '17.194.226.42', 'MPP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('SSMPSBCN05', 'MPP', '17.194.226.43', 'MPP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('SSMPSBDN06', 'MPP', '17.194.226.44', 'MPP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('SSMPSBDN07', 'MPP', '17.194.226.45', 'MPP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('SSMPSBDN08', 'MPP', '17.194.226.46', 'MPP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('SSMPSBDN09', 'MPP', '17.194.226.59', 'MPP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('SSMPSBDN10', 'MPP', '17.194.226.52', 'MPP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('SSMPSBDN11', 'MPP', '17.194.226.53', 'MPP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('SSMPSBDN12', 'MPP', '17.194.226.65', 'MPP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('SSRVLSSLB', 'NetSign', '17.194.157.24', 'NetSign', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('SSRVSSLA', 'NetSign', '17.194.141.24', 'NetSign', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('STDBDG04', 'DBRG', '17.194.131.17', 'DBRG', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('STDBDG05', 'DBRG', '17.194.147.17', 'DBRG', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('STDBDG06', 'DBRG', '17.194.147.18', 'DBRG', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('W0105GWA01_NEW', 'EAP', '17.195.209.28', 'EAP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('W0105GWA02_NEW', 'EAP', '17.195.209.29', 'EAP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('W0301GWA01', 'EAP', '17.195.209.32', 'EAP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('W0301GWA02_NEW', 'EAP', '17.195.209.33', 'EAP', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('WNPFEA01_NEW', 'NPFE/NIFE', '17.195.209.1', 'NPFE/NIFE', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('WNPFEA02_NEW', 'NPFE/NIFE', '17.195.209.2', 'NPFE/NIFE', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('WNPFEB01_NEW', 'NPFE/NIFE', '17.195.209.3', 'NPFE/NIFE', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('WNPFEB02_NEW', 'NPFE/NIFE', '17.195.209.4', 'NPFE/NIFE', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('WPMTSAPA_V43', 'PMTSNPC', '17.195.203.1', 'PMTSNPC', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('WPMTSAPB_V43', 'PMTSNPC', '17.195.203.2', 'PMTSNPC', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('WPMTSAPC_V43', 'PMTSNPC', '17.195.203.3', 'PMTSNPC', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('WPMTSAPD_V43', 'PMTSNPC', '17.195.203.4', 'PMTSNPC', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('WPMTSAPE_V43', 'PMTSNPC', '17.195.203.5', 'PMTSNPC', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('WPMTSAPF_V43', 'PMTSNPC', '17.195.203.6', 'PMTSNPC', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('WSRVSSLA', 'NetSign', '17.195.141.24', 'NetSign', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('WSRVSSLB', 'NetSign', '17.195.157.24', 'NetSign', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('sb-netsign-06', 'NetSign', '17.194.157.36', 'NetSign', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('sb-netsign-07', 'NetSign', '17.194.157.41', 'NetSign', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('sz-netsign-06', 'NetSign', '17.194.141.36', 'NetSign', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('sz-netsign-07', 'NetSign', '17.194.141.41', 'NetSign', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('wb-netsign-06', 'NetSign', '17.195.106.38', 'NetSign', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('wb-netsign-07', 'NetSign', '17.195.106.36', 'NetSign', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('wz-netsign-06', 'NetSign', '17.195.106.37', 'NetSign', 1, 0, null);
INSERT INTO zt_partition (name, application, ip, applicationName, dataOrigin, deleted, deletedDate) VALUES ('wz-netsign-07', 'NetSign', '17.195.106.35', 'NetSign', 1, 0, null);